// Episode: The Origin Story
// Scripture: Matt 4:18-22 · John 1:35-51 · Matt 9:9-13 · Luke 6:12-16
window.EPISODES.push({
  id: "origin",
  title: "The Origin Story",
  subtitle: "How the group chat came together",
  emoji: "⛵➡️🐟",
  location: "Sea of Galilee → Various",
  scripture: "Matt 4:18-22 · John 1:35-51 · Matt 9:9-13 · Luke 6:12-16",
  time: "7:12 AM",
  battery: 95,
  headerName: "Fishers of Men 🐟",
  dynamicHeader: true,
  messages: [
  { type: "system", text: "Jesus created the group" },
  { type: "system", text: "Jesus added Peter" },
  { type: "system", text: "Jesus added Andrew" },
  { type: "system", text: "Jesus named the group \"Fishers of Men 🐟\"" },
  { sender: "Peter", color: "#60A5FA", msg: "so we're really doing this?? we're really just leaving the nets and following him??", time: "7:12 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "peter we literally watched him speak for five minutes and you dropped your net mid-catch", time: "7:13 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "it was a bad catch anyway", time: "7:13 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "it was the best catch of your life. you pulled up so many fish the boat almost sank.", time: "7:14 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok THAT'S why i left. if he can do THAT to fish he can do anything. i'm in. i'm so in.", time: "7:14 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "you don't have to convince me i'm literally already here", time: "7:15 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "what do we even do tho. like what's the job description.", time: "7:16 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he said \"follow me and I will make you fishers of men\"", time: "7:16 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "that goes so hard", time: "7:17 AM" },
  { type: "system", text: "Jesus added James" },
  { type: "system", text: "Jesus added John" },
  { sender: "Peter", color: "#60A5FA", msg: "YOOO the Zebedee boys!! welcome!! 🎉", time: "8:45 AM" },
  { sender: "James", color: "#2DD4BF", msg: "what's up. we're in. just left the boat.", time: "8:46 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "wait did you guys just leave your dad in the boat by himself?? 😭", time: "8:46 AM" },
  { sender: "John", color: "#34D399", msg: "he has the hired men he'll be fine", time: "8:47 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he's gonna be mad for like a week and then he'll get over it", time: "8:47 AM" },
  { sender: "John", color: "#34D399", msg: "we didn't even finish mending the nets lol", time: "8:48 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "you left your father holding half-mended nets on a boat watching his two sons walk away 💀", time: "8:48 AM" },
  { sender: "James", color: "#2DD4BF", msg: "when the Messiah calls you don't ask him to wait while you finish your chores andrew", time: "8:49 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok so we're four now. this is a SQUAD.", time: "8:50 AM" },
  { sender: "John", color: "#34D399", msg: "all fishermen too. very on brand for the group name", time: "8:51 AM" },
  { type: "system", text: "A few days later" },
  { type: "system", text: "Jesus added Philip" },
  { sender: "Philip", color: "#C084FC", msg: "hey everyone! Jesus literally just walked up to me and said \"Follow me.\" two words. that's all it took apparently.", time: "2:15 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "welcome!! that's basically how it went for all of us lol", time: "2:16 PM" },
  { sender: "Philip", color: "#C084FC", msg: "ok i already have a guy we need to add. my friend Nathanael. he's the real deal. hold on i'm going to get him.", time: "2:18 PM" },
  { sender: "James", color: "#2DD4BF", msg: "philip has been here 3 minutes and is already recruiting 😂", time: "2:19 PM" },
  { sender: "Philip", color: "#C084FC", msg: "ok slight issue. i told Nathanael that we found the one Moses wrote about — Jesus of Nazareth — and he said... um...", time: "2:30 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what did he say", time: "2:30 PM" },
  { sender: "Philip", color: "#C084FC", msg: "\"Can anything good come from Nazareth?\" 😬", time: "2:31 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "WOW", time: "2:31 PM" },
  { sender: "John", color: "#34D399", msg: "that is WILD. he said that about Nazareth? out loud?", time: "2:32 PM" },
  { sender: "James", color: "#2DD4BF", msg: "not the Nazareth slander 💀", time: "2:32 PM" },
  { sender: "Philip", color: "#C084FC", msg: "i just said \"come and see\" and he's coming. but brace yourselves he has opinions.", time: "2:33 PM" },
  { sender: "Philip", color: "#C084FC", msg: "OK UPDATE. Jesus just saw Nathanael walking up and said \"Here truly is an Israelite in whom there is no deceit\" and Nathanael said \"how do you know me?\" and Jesus said \"I saw you under the fig tree before Philip called you\"", time: "2:40 PM" },
  { sender: "Philip", color: "#C084FC", msg: "and Nathanael is SHOOK. like white as a sheet.", time: "2:40 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what was he doing under the fig tree??", time: "2:41 PM" },
  { sender: "Philip", color: "#C084FC", msg: "idk but whatever it was it was private enough that Jesus knowing about it broke his brain", time: "2:41 PM" },
  { sender: "Philip", color: "#C084FC", msg: "he just said \"Rabbi, you are the Son of God! You are the King of Israel!\" HE WENT FROM NAZARETH SLANDER TO SON OF GOD IN FOUR MINUTES", time: "2:42 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "speedrun conversion any% 😂", time: "2:42 PM" },
  { type: "system", text: "Jesus added Nathanael" },
  { sender: "Nathanael", color: "#FB923C", msg: "before anyone says anything. yes i said the Nazareth thing. i was wrong. we're moving on.", time: "2:45 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "oh we are absolutely NOT moving on 😂", time: "2:45 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i had preconceived notions and they were incorrect. growth.", time: "2:46 PM" },
  { sender: "John", color: "#34D399", msg: "\"can anything good come from Nazareth\" is going to follow you forever btw", time: "2:46 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "cool cool cool", time: "2:47 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "also what were you doing under that fig tree 👀", time: "2:47 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "NONE OF YOUR BUSINESS PETER", time: "2:47 PM" },
  { type: "system", text: "Peter renamed the group \"Fishers of Men (now with non-fishermen)\"" },
  { sender: "Philip", color: "#C084FC", msg: "that name is terrible", time: "2:50 PM" },
  { type: "system", text: "Several weeks later" },
  { sender: "Peter", color: "#60A5FA", msg: "ok Jesus said he's adding someone new today. another tax booth situation. he's heading over to the customs post rn.", time: "10:30 AM" },
  { sender: "James", color: "#2DD4BF", msg: "a tax collector???", time: "10:31 AM" },
  { sender: "John", color: "#34D399", msg: "like... a Roman tax collector? one of THOSE guys?", time: "10:31 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "this should be interesting", time: "10:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he walked up to the booth, looked at the guy, and said \"Follow me.\" same two words. the tax collector just STOOD UP and LEFT. didn't even close his cash box.", time: "10:38 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "he left an open cash box?? in the market??", time: "10:39 AM" },
  { sender: "James", color: "#2DD4BF", msg: "i have concerns about adding a tax collector to this group tbh. these guys are not popular.", time: "10:39 AM" },
  { sender: "John", color: "#34D399", msg: "\"not popular\" is doing a lot of heavy lifting there james. people HATE tax collectors.", time: "10:40 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "well Jesus picked him so i trust it. even if it's weird.", time: "10:41 AM" },
  { type: "system", text: "Jesus added Matthew" },
  { sender: "Matthew", color: "#818CF8", msg: "hi everyone. i know what you're all thinking. yes i was a tax collector. yes i worked for Rome. i'm aware of how that looks.", time: "10:44 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "in my defense i am very good with numbers and recordkeeping", time: "10:44 AM" },
  { sender: "James", color: "#2DD4BF", msg: "you were good at taking people's money is what you were good at", time: "10:45 AM" },
  { sender: "John", color: "#34D399", msg: "james", time: "10:45 AM" },
  { sender: "James", color: "#2DD4BF", msg: "i'm just saying what everyone is thinking", time: "10:46 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "no that's fair. i deserve that.", time: "10:46 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok let's reset. matthew welcome to the group. jesus chose you and that's good enough for us. right everyone?", time: "10:47 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "right", time: "10:47 AM" },
  { sender: "Philip", color: "#C084FC", msg: "welcome matthew 👋", time: "10:48 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "welcome. at least you're not from Nazareth 😂", time: "10:48 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "LMAOOO nathanael finally passing the joke to someone else", time: "10:49 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "also i'm throwing a dinner party at my house tonight for Jesus and you're all invited. i have a LOT of tax collector friends coming too btw. just so you know.", time: "10:52 AM" },
  { sender: "James", color: "#2DD4BF", msg: "a house full of tax collectors. amazing.", time: "10:53 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the food will be incredible though. we make good money.", time: "10:53 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "made. made good money. past tense. i'm reformed.", time: "10:54 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "😂😂😂", time: "10:54 AM" },
  { type: "system", text: "Over the following weeks" },
  { type: "system", text: "Jesus added Thomas" },
  { sender: "Thomas", color: "#A78BFA", msg: "hi. quick question before i get settled. is there a formal onboarding process or are we just winging it.", time: "3:20 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "we're winging it", time: "3:21 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "that tracks. follow up question. what's the mission statement.", time: "3:21 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "follow Jesus", time: "3:22 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok but like WHERE. for how long. what are the deliverables.", time: "3:22 PM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas you've been here 4 minutes", time: "3:23 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "and i already have questions. you should be concerned that nobody else does.", time: "3:23 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "i like this guy actually. someone should be asking questions.", time: "3:24 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "you will regret saying that matthew", time: "3:24 PM" },
  { type: "system", text: "Jesus added James (son of Alphaeus)" },
  { sender: "James", color: "#2DD4BF", msg: "wait there's two James now??", time: "4:10 PM" },
  { sender: "James (son of Alphaeus)", color: "#6EE7B7", msg: "hey everyone! yes another James. sorry about that lol", time: "4:11 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok we need a system. you're Big James and you're Little James. no offense.", time: "4:12 PM" },
  { sender: "James (son of Alphaeus)", color: "#6EE7B7", msg: "some offense taken but ok", time: "4:12 PM" },
  { sender: "James", color: "#2DD4BF", msg: "i accept Big James. that's my brand now.", time: "4:13 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "shouldn't we use last names? or father's names? this is a solvable organizational problem.", time: "4:14 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "Big James and Little James is fine thomas", time: "4:14 PM" },
  { type: "system", text: "Jesus added Thaddaeus" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "hey! excited to be here. what have i missed.", time: "4:30 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "honestly a lot. just scroll up. take your time.", time: "4:31 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "who said the Nazareth thing 😂", time: "4:36 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i will leave this group", time: "4:36 PM" },
  { type: "system", text: "Jesus added Simon the Zealot" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "what's up everyone. Simon the Zealot here. yes that kind of zealot. anti-Rome all day. 🔥", time: "5:02 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "oh no", time: "5:03 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "oh this is going to be interesting", time: "5:03 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "why is everyone being weird", time: "5:04 PM" },
  { sender: "John", color: "#34D399", msg: "simon meet matthew. matthew was a tax collector. for Rome.", time: "5:04 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he was WHAT", time: "5:05 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "WAS. past tense. i've been saying past tense a lot lately.", time: "5:05 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "Jesus really put a zealot and a tax collector in the same group chat. this man has a sense of humor.", time: "5:06 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the tension in here could cut marble 😂", time: "5:06 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "should we establish some ground rules for political discussions or", time: "5:07 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "probably yes thomas. for once you're right.", time: "5:07 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "fine. but i'm watching you matthew.", time: "5:08 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "fair", time: "5:08 PM" },
  { type: "system", text: "Peter renamed the group \"The Squad 🐟\" " },
  { sender: "John", color: "#34D399", msg: "peter you can't keep changing the group name", time: "5:10 PM" },
  { type: "system", text: "A few days later" },
  { type: "system", text: "Jesus added Judas" },
  { sender: "Judas", color: "#94A3B8", msg: "hello everyone. Judas Iscariot. happy to be here. i have experience managing funds if the group needs a treasurer.", time: "11:20 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "oh i can do treasurer. i have extensive financial background.", time: "11:21 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "yeah stealing from people 😐", time: "11:21 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "SIMON", time: "11:22 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "let's give judas the money bag. fresh start. no baggage.", time: "11:23 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "should we not have some kind of vetting process for who handles the money? background checks? references?", time: "11:24 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas he was literally chosen by Jesus", time: "11:24 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "Jesus chose all of us. i'm asking about ACCOUNTING specifically.", time: "11:25 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i assure you the money will be in good hands 🙂", time: "11:26 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "great! that's settled. judas has the money bag.", time: "11:27 AM" },
  { type: "system", text: "Peter renamed the group \"The Twelve 🐟\"" },
  { sender: "Peter", color: "#60A5FA", msg: "WE'RE FULL. TWELVE DISCIPLES. THIS IS THE ROSTER.", time: "11:30 AM" },
  { sender: "John", color: "#34D399", msg: "ok that name actually works", time: "11:30 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "shouldn't Jesus have named the group? he started it.", time: "11:31 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i'm taking initiative thomas. leadership.", time: "11:31 AM" },
  { sender: "James", color: "#2DD4BF", msg: "nobody appointed you leader peter", time: "11:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i was the FIRST one added", time: "11:32 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "actually we were added at the same time peter", time: "11:33 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "my name was first in the notification", time: "11:33 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "that's alphabetical peter", time: "11:33 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "it is absolutely not alphabetical. Andrew comes before Peter.", time: "11:34 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok REGARDLESS. we're twelve. this is the team. let's go change the world.", time: "11:35 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "do we have a plan for that or", time: "11:35 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "we follow Jesus thomas", time: "11:36 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "right but like a ROADMAP. quarterly goals. KPIs.", time: "11:36 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas i'm begging you", time: "11:37 AM" },
  { type: "system", text: "Later that week" },
  { type: "system", text: "Peter added Mary Magdalene" },
  { type: "system", text: "Peter added Mary (mother of James)" },
  { sender: "Peter", color: "#60A5FA", msg: "ok the group chat needed some balance. welcome ladies 🎉", time: "9:15 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i've been following Jesus longer than half of you but sure thanks for finally adding me to the chat peter 💅", time: "9:16 AM" },
  { sender: "John", color: "#34D399", msg: "she's got a point 😂", time: "9:16 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "she really does", time: "9:17 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "also i just scrolled through the entire history. the Nazareth slander. the fig tree mystery. matthew's tax collector dinner party. simon and matthew's beef. thomas asking for KPIs. this group is unhinged and i love it.", time: "9:20 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "can we PLEASE stop bringing up the Nazareth thing", time: "9:21 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "absolutely not. that's the best thing in this chat.", time: "9:21 AM" },
  { type: "system", text: "John renamed the group \"The Twelve (+) 🐟\"" },
  { sender: "Peter", color: "#60A5FA", msg: "john that's perfect actually", time: "9:23 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "the (+) is doing A LOT of heavy lifting but i'll allow it", time: "9:24 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "for the record i think we need a more descriptive group name. something with a mission statement.", time: "9:25 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "thomas if you say KPIs one more time i'm muting you", time: "9:25 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "this organization has no structure and it's going to be a problem", time: "9:26 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "oh i'm going to love it here", time: "9:26 AM" },
  { type: "system", text: "Read by everyone" },
],
});
