// Episode: The Wedding at Cana
// Scripture: John 2:1-12
window.EPISODES.push({
  id: "cana",
  title: "The Wedding at Cana",
  subtitle: "His mom wouldn't take no for an answer",
  emoji: "🍷💧➡️🍷",
  location: "Cana, Galilee",
  scripture: "John 2:1-12",
  time: "4:30 PM",
  battery: 55,
  messages: [
  { type: "system", text: "Today, 4:30 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "wedding day!! we got invited to a wedding in Cana. free food free wine. this is the best day since i joined.", time: "4:30 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the venue is actually nice. someone's family has money.", time: "4:31 PM" },
  { sender: "John", color: "#34D399", msg: "Jesus's mom is here too. she seems to know the family pretty well.", time: "4:32 PM" },
  { sender: "James", color: "#2DD4BF", msg: "the food is incredible. whoever catered this went OFF.", time: "4:33 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have to say the wine selection is excellent. very solid vintage.", time: "4:34 PM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas is a wine critic now apparently 😂", time: "4:34 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have opinions about things philip. this is not new.", time: "4:35 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i'm from Cana btw. this is my hometown. so everyone please behave.", time: "4:36 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "we always behave nathanael", time: "4:36 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "you do not. you literally never do.", time: "4:37 PM" },
  { type: "system", text: "6:45 PM" },
  { sender: "John", color: "#34D399", msg: "uh oh", time: "6:45 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what", time: "6:45 PM" },
  { sender: "John", color: "#34D399", msg: "overheard the servants talking. they're out of wine.", time: "6:46 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "OUT?? the wedding isn't even close to over. how do you run out of wine at a WEDDING.", time: "6:46 PM" },
  { sender: "James", color: "#2DD4BF", msg: "this is a catastrophic planning failure. the groom's family is going to be humiliated.", time: "6:47 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "this is exactly what happens when you don't do proper capacity planning. how many guests. how many days. how many liters per person per day. it's basic math.", time: "6:47 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "in the groom's defense, some of us drink more than average", time: "6:48 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "was that directed at me matthew", time: "6:48 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "i didn't say names peter but you're on your fourth cup and we've been here two hours", time: "6:49 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "this is my HOMETOWN wedding and you guys drank them dry. i am mortified.", time: "6:50 PM" },
  { sender: "John", color: "#34D399", msg: "ok so. Mary just found out about the wine situation.", time: "6:52 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "uh oh", time: "6:52 PM" },
  { sender: "John", color: "#34D399", msg: "she went straight to Jesus.", time: "6:53 PM" },
  { sender: "John", color: "#34D399", msg: "she just said \"They have no wine.\" that's it. just looked at him and said it.", time: "6:53 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "that is classic mom energy. she didn't ask him to do anything. she just STATED THE PROBLEM and let the implication hang.", time: "6:54 PM" },
  { sender: "James", color: "#2DD4BF", msg: "the way moms can give you an assignment without technically giving you an assignment is an art form", time: "6:54 PM" },
  { sender: "John", color: "#34D399", msg: "Jesus just said \"Woman, why do you involve me? My hour has not yet come.\"", time: "6:55 PM" },
  { sender: "Philip", color: "#C084FC", msg: "oh he tried to say no", time: "6:55 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "tried 😂", time: "6:56 PM" },
  { sender: "John", color: "#34D399", msg: "Mary didn't even flinch. she turned to the servants and said \"Do whatever he tells you.\"", time: "6:56 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "SHE IGNORED THE NO. SHE WENT STRAIGHT TO THE STAFF. 😭😭😭", time: "6:57 PM" },
  { sender: "James", color: "#2DD4BF", msg: "she just project-managed her son into a miracle. delegated around his objection.", time: "6:57 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "he said his hour has not yet come. she said it has. and apparently she outranks him on this??", time: "6:58 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "she's his MOM thomas. moms always outrank.", time: "6:58 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the Son of God just got mom'd. i am witnessing history.", time: "6:59 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "Mary is the most powerful person in this building and it's not close", time: "6:59 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "\"do whatever he tells you\" is giving absolute confidence that her son is about to handle it whether he wants to or not 😂", time: "7:00 PM" },
  { sender: "John", color: "#34D399", msg: "ok something's happening. Jesus is talking to the servants. he's pointing at the stone water jars.", time: "7:03 PM" },
  { sender: "Philip", color: "#C084FC", msg: "those are the purification jars. they're massive. like 20-30 gallons EACH. and there's SIX of them.", time: "7:04 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "those are for ceremonial washing. not drinking. what is he doing.", time: "7:04 PM" },
  { sender: "John", color: "#34D399", msg: "he told the servants to fill them with water. to the brim.", time: "7:05 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "fill the WASHING jars with WATER when the problem is NO WINE?? how does that help 😭", time: "7:06 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the servants look so confused rn but they're doing it. Mary's standing there watching with this look on her face like she knows something.", time: "7:07 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "pouring water into stone jars is not a wine solution. i want to be supportive but this is concerning.", time: "7:08 PM" },
  { sender: "James", color: "#2DD4BF", msg: "thomas just wants to be supportive 😂", time: "7:08 PM" },
  { sender: "John", color: "#34D399", msg: "they're full. all six. to the brim.", time: "7:10 PM" },
  { sender: "John", color: "#34D399", msg: "now he told them to draw some out and take it to the master of the banquet.", time: "7:10 PM" },
  { sender: "Philip", color: "#C084FC", msg: "they're going to bring the party planner a cup of WATER and say it's wine?? this is about to be so embarrassing for everyone involved.", time: "7:11 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the servant carrying the cup looks TERRIFIED. he thinks he's about to lose his job.", time: "7:12 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "wait", time: "7:13 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "WAIT", time: "7:13 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the master of the banquet just TASTED it", time: "7:13 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "his face 😭😭😭", time: "7:14 PM" },
  { sender: "John", color: "#34D399", msg: "HE LIKES IT. HE LOVES IT. HE'S CALLING THE GROOM OVER.", time: "7:14 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "IT'S WINE. THE WATER IS WINE. IT'S ACTUAL WINE.", time: "7:14 PM" },
  { sender: "James", color: "#2DD4BF", msg: "WHAT 😂😂😂😂😂", time: "7:15 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i'm sorry. i need to process. he turned water. into wine. actual wine. that people are drinking.", time: "7:15 PM" },
  { sender: "Philip", color: "#C084FC", msg: "SIX JARS. 20-30 GALLONS EACH. THAT'S OVER 150 GALLONS OF WINE. FROM WATER.", time: "7:16 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "they ran out of wine and he made enough to supply a SECOND wedding 💀", time: "7:16 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "the master of the banquet just told the groom \"Everyone brings out the choice wine first and then the cheaper wine after the guests have had too much to drink, but you have saved the best till now.\"", time: "7:17 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "wait. it's not just wine. it's the BEST wine?? better than what they started with???", time: "7:18 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he didn't just solve the problem. he UPGRADED the problem. they had decent wine and he replaced it with the BEST WINE ANYONE HAS EVER TASTED.", time: "7:18 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok i have many questions. was it wine the moment it entered the jar? was it wine when it was poured? at what point in the journey from jar to cup did it stop being water and become wine? this matters.", time: "7:19 PM" },
  { sender: "John", color: "#34D399", msg: "thomas i beg you to just drink the miracle wine", time: "7:19 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i AM drinking it. it's delicious. i just also have questions.", time: "7:20 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the groom is getting ALL the credit rn btw. everyone thinks he saved the best wine for last. he has NO idea what happened. he's just standing there like 😊 accepting compliments.", time: "7:21 PM" },
  { sender: "James", color: "#2DD4BF", msg: "imagine getting credit for a miracle you didn't do at your own wedding. this man's marriage is starting with a cheat code 😂", time: "7:22 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "Mary is just sitting there sipping wine with the most satisfied look i've ever seen on a human face.", time: "7:23 PM" },
  { sender: "Philip", color: "#C084FC", msg: "she knew. she KNEW the whole time. \"do whatever he tells you.\" she didn't even hesitate.", time: "7:24 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the servant who carried the cup is standing in the corner looking like he's seen a ghost. someone go check on him.", time: "7:25 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "that man poured water out of a washing jar and watched wine come out. his whole worldview just collapsed.", time: "7:25 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "so nobody at this wedding knows what just happened except us, the servants, and Mary. the greatest miracle ever performed and it happened behind the scenes at a catering crisis.", time: "7:27 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "his first miracle. and it was at a party. to save a family from embarrassment. because his mom told him to.", time: "7:28 PM" },
  { sender: "James", color: "#2DD4BF", msg: "that's honestly perfect. his first miracle wasn't parting a sea or raining fire. it was making sure people had enough wine at a wedding. because he cared about the little stuff.", time: "7:29 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "that is actually beautiful. no notes. well. one note. i'd like to know the exact moment of molecular transformation but i'll let it go.", time: "7:30 PM" },
  { sender: "John", color: "#34D399", msg: "he won't let it go", time: "7:30 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i will NOT let it go but i'm SAYING i will", time: "7:31 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "does anyone know what that wine would be worth on the open market? 150 gallons of the best wine anyone's ever tasted? i'm just asking for budgeting purposes.", time: "7:33 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "JUDAS", time: "7:33 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "BUDGETING PURPOSES", time: "7:34 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "so let me get this straight. Jesus said no. Mary said yes. Mary won. he turned 150 gallons of water into the best wine in history. nobody at the party knows. the groom is getting credit. and we're all just sitting here drinking miracle wine at a wedding.", time: "7:36 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "in MY hometown btw. can anything good come from Nazareth? apparently YES. yes it can. 150 gallons of it.", time: "7:37 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "HE BROUGHT BACK THE NAZARETH THING 😂😂😂", time: "7:37 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i've been waiting MONTHS to redeem that and this was the perfect moment", time: "7:38 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "so his first miracle was at a party, to prevent social embarrassment, because his mom peer pressured him into it, and he made 150 gallons of the best wine anyone's ever had?? i picked the right guy to follow. 💅", time: "7:42 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "writing it all down. first chapter. the one where his mom wouldn't take no for an answer. 🍷", time: "7:43 PM" },
  { type: "system", text: "Read by everyone" },
],
});
