// Episode: Through the Roof
// Scripture: Mark 2:1-12 · Luke 5:17-26
window.EPISODES.push({
  id: "roof",
  title: "Through the Roof",
  subtitle: "Four friends, one roof, zero permission",
  emoji: "🕳️🛏️⬇️",
  location: "Capernaum",
  scripture: "Mark 2:1-12 · Luke 5:17-26",
  time: "10:05 AM",
  battery: 80,
  messages: [
  { type: "system", text: "Today, 10:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus is teaching at my house today. just a heads up the place is PACKED. standing room only. people in the doorway. people outside the windows.", time: "10:05 AM" },
  { sender: "John", color: "#34D399", msg: "there is literally not one more square inch of space in this house", time: "10:06 AM" },
  { sender: "James", color: "#2DD4BF", msg: "pharisees got the good seats btw. front row. taking notes. looking judgmental. the usual.", time: "10:07 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "has anyone done a capacity check. this feels like a fire hazard.", time: "10:08 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "there are no fire codes thomas. it's capernaum.", time: "10:08 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "there SHOULD be fire codes. this is a safety issue.", time: "10:09 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "can everyone just focus. he's teaching. it's really good.", time: "10:10 AM" },
  { type: "system", text: "10:22 AM" },
  { sender: "Philip", color: "#C084FC", msg: "ok so there's a commotion outside", time: "10:22 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "four guys just showed up carrying their friend on a mat. he's paralyzed. they're trying to get inside.", time: "10:23 AM" },
  { sender: "John", color: "#34D399", msg: "they can't get in. not even close. the crowd is too deep.", time: "10:24 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "they look really desperate. they're arguing with people at the door trying to push through.", time: "10:25 AM" },
  { sender: "James", color: "#2DD4BF", msg: "honestly feel bad for them. they carried this guy all the way here and can't even get in.", time: "10:25 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "they're leaving. looks like they gave up.", time: "10:27 AM" },
  { sender: "Philip", color: "#C084FC", msg: "wait no they're not leaving. they're going around the side of the house.", time: "10:27 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what are they doing", time: "10:28 AM" },
  { sender: "Philip", color: "#C084FC", msg: "they're. um.", time: "10:28 AM" },
  { sender: "Philip", color: "#C084FC", msg: "they're going up the stairs to the roof.", time: "10:28 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "MY roof???", time: "10:29 AM" },
  { sender: "Philip", color: "#C084FC", msg: "your roof peter.", time: "10:29 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "WHY ARE THEY ON MY ROOF", time: "10:29 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "carrying a paralyzed man. up stairs. on a mat. i have to respect the engineering of this but i don't understand the strategy.", time: "10:30 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "those are RIDE OR DIE friends. most people would've said \"sorry bro it's too crowded let's come back tomorrow.\" these guys said \"we're going UP.\"", time: "10:31 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "they're on the roof now. all four of them. plus the guy on the mat.", time: "10:32 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what are they gonna do just stand up there", time: "10:32 AM" },
  { sender: "John", color: "#34D399", msg: "uh", time: "10:33 AM" },
  { sender: "John", color: "#34D399", msg: "guys", time: "10:33 AM" },
  { sender: "John", color: "#34D399", msg: "they're digging through the roof.", time: "10:33 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "THEY'RE DOING WHAT", time: "10:34 AM" },
  { sender: "John", color: "#34D399", msg: "DIGGING. THROUGH. THE. ROOF. with their hands. pulling apart the tiles and mud.", time: "10:34 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "THAT IS MY ROOF. I OWN THAT ROOF. THOSE ARE MY TILES.", time: "10:34 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "debris is falling into the room 😭", time: "10:35 AM" },
  { sender: "James", color: "#2DD4BF", msg: "mud and straw just landed on a pharisee's head 💀", time: "10:35 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "ANOTHER pharisee got hit. they are NOT happy. brushing dirt off their robes looking absolutely OFFENDED.", time: "10:36 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "i can see sky through the ceiling now. there's an actual hole forming in the middle of the room. this is INSANE.", time: "10:36 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "I JUST FIXED THAT ROOF LAST MONTH", time: "10:37 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "peter i know this is your house but this is genuinely the hardest thing i've ever watched. these men are DESTROYING ARCHITECTURE for their friend.", time: "10:37 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "MY architecture simon. MINE.", time: "10:38 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "structurally speaking they're weakening the load-bearing capacity of the entire roof. if they go much further the whole thing could collapse.", time: "10:38 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas NOT HELPING", time: "10:39 AM" },
  { sender: "Philip", color: "#C084FC", msg: "the hole is big enough now. they're tying ropes to the corners of the mat.", time: "10:40 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "oh my God they're going to LOWER him down", time: "10:40 AM" },
  { sender: "John", color: "#34D399", msg: "THEY'RE LOWERING HIM THROUGH THE CEILING. a paralyzed man. on a mat. on ropes. through a hole in the roof. into the middle of a sermon.", time: "10:41 AM" },
  { sender: "James", color: "#2DD4BF", msg: "this is the most dramatic entrance in HISTORY. every eye in the room is on this man slowly descending from the ceiling like a chandelier 😭", time: "10:42 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "he's dangling. he's just dangling there. spinning slightly. looking absolutely terrified.", time: "10:42 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the people below him are scrambling out of the way. a pharisee just dove sideways to avoid getting landed on 💀", time: "10:43 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "pharisee DOVE 😂😂😂", time: "10:43 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "there is a man being lowered through my ceiling on ropes. there is rubble all over my floor. my house is an open-air venue now. this is fine.", time: "10:44 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "peter is going through the five stages of grief about his roof in real time", time: "10:44 AM" },
  { sender: "Philip", color: "#C084FC", msg: "he's down. he's on the ground. right at Jesus's feet. the four friends are peering down through the hole.", time: "10:45 AM" },
  { sender: "John", color: "#34D399", msg: "ok everyone shut up. look at Jesus's face.", time: "10:46 AM" },
  { sender: "John", color: "#34D399", msg: "he's looking UP. at the four guys. through the hole. and he's SMILING.", time: "10:46 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "it says he saw their FAITH. not the paralyzed man's faith. THEIR faith. the friends' faith. the four guys who destroyed a roof.", time: "10:47 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "that is wrecking me. their faith was so strong it counted for their friend. i'm not ok.", time: "10:48 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he just said to the paralyzed man: \"Son, your sins are forgiven.\"", time: "10:49 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "wait. sins? they brought him to be HEALED. why is he talking about sins?", time: "10:49 AM" },
  { sender: "James", color: "#2DD4BF", msg: "the pharisees are LOSING it rn. whispering to each other. i can practically hear them thinking \"ONLY GOD can forgive sins.\"", time: "10:50 AM" },
  { sender: "John", color: "#34D399", msg: "Jesus just looked at the pharisees and said \"Why are you thinking these things in your hearts?\"", time: "10:51 AM" },
  { sender: "Philip", color: "#C084FC", msg: "HE READ THEIR MINDS 😭", time: "10:51 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "they didn't even say anything OUT LOUD and he still caught them 💀", time: "10:52 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he said \"Which is easier: to say 'Your sins are forgiven,' or to say 'Get up and walk'?\"", time: "10:53 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "oh that's brilliant. anyone can SAY sins are forgiven because you can't prove it. but saying get up and walk — that's immediately verifiable. he's using the visible miracle to prove the invisible one.", time: "10:54 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "thomas just had the best theological take of his entire career and i need everyone to acknowledge it", time: "10:54 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"But I want you to know that the Son of Man has authority on earth to forgive sins.\" and then he looked at the man and said", time: "10:56 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"I tell you, get up, take your mat and go home.\"", time: "10:56 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "guys", time: "10:57 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he's moving his legs", time: "10:57 AM" },
  { sender: "John", color: "#34D399", msg: "HE'S STANDING UP", time: "10:57 AM" },
  { sender: "James", color: "#2DD4BF", msg: "HE IS ON HIS FEET. IN FULL VIEW OF EVERYONE.", time: "10:58 AM" },
  { sender: "Philip", color: "#C084FC", msg: "THE WHOLE ROOM IS SCREAMING", time: "10:58 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "a man who was CARRIED in on a mat is STANDING and PICKING UP the mat he was laying on. i am going to pass out.", time: "10:59 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "he's WALKING. HE'S WALKING OUT. CARRYING HIS OWN MAT. THROUGH THE CROWD. PEOPLE ARE FALLING OVER THEMSELVES TO GET OUT OF HIS WAY.", time: "10:59 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "the four friends on the roof are absolutely LOSING it. one of them is laying face down on the roof sobbing. another one is jumping up and down which is making the whole roof shake.", time: "11:00 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "PLEASE STOP JUMPING ON MY ROOF", time: "11:00 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have zero questions. a paralyzed man walked. that's all there is to say.", time: "11:01 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "people are saying \"We have never seen anything like this.\" which is the understatement of the century. a man flew in through the ceiling and walked out through the door.", time: "11:02 AM" },
  { sender: "James", color: "#2DD4BF", msg: "\"flew in through the ceiling and walked out through the door\" is absolutely going on his tombstone 😭", time: "11:03 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "that was the most incredible thing i've ever witnessed. genuinely. i am in awe.", time: "11:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "but also who is fixing my roof. because someone is fixing my roof.", time: "11:05 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the man can WALK peter. your roof can wait.", time: "11:06 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the man can walk AND my roof has a hole in it. both things are true andrew.", time: "11:06 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "if it rains tonight peter's house is going to be an indoor pool", time: "11:07 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "does anyone know if the four friends have money because someone should be invoicing them for the roof repair. i can draft something.", time: "11:08 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "judas those men just demonstrated the greatest act of friendship in human history and you want to INVOICE them", time: "11:09 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "friendship doesn't fix roofs simon", time: "11:09 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "so four guys destroyed peter's ceiling, lowered their friend into a sermon like a human piñata, Jesus forgave his sins AND healed him, the pharisees got dirt in their hair, and now peter is trying to bill someone for roof damage?? i love this group chat more than anything on earth. 💅", time: "11:14 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"human piñata\" is INSANE mary", time: "11:14 AM" },
  { type: "system", text: "Read by everyone" },
],
});
