// Episode: The Sermon on the Mount
// Scripture: Matthew 5-7 · Luke 6:17-49
window.EPISODES.push({
  id: "sermon",
  title: "The Sermon on the Mount",
  subtitle: "Blessed are the confused",
  emoji: "⛰️🧂💡",
  location: "A Mountainside in Galilee",
  scripture: "Matthew 5-7 · Luke 6:17-49",
  time: "8:30 AM",
  battery: 90,
  messages: [
  { type: "system", text: "Today, 8:30 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus is heading up the mountainside. huge crowd following. i think he's about to teach.", time: "8:30 AM" },
  { sender: "John", color: "#34D399", msg: "nice spot honestly. great view. good acoustics.", time: "8:31 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "did anyone bring something to write with. this feels important.", time: "8:32 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "i always have something to write with thomas. always.", time: "8:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he sat down. he's starting.", time: "8:35 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"Blessed are the poor in spirit, for theirs is the kingdom of heaven.\"", time: "8:36 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "what does poor in spirit mean. like sad? broke emotionally? spiritually bankrupt?", time: "8:36 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas he JUST started", time: "8:37 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"Blessed are the meek, for they will inherit the earth.\"", time: "8:38 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the MEEK?? the meek get conquered. that's historically what happens to the meek.", time: "8:39 AM" },
  { sender: "James", color: "#2DD4BF", msg: "simon maybe don't argue with the sermon in real time", time: "8:39 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"Blessed are the peacemakers\" 👀", time: "8:41 AM" },
  { sender: "John", color: "#34D399", msg: "simon he's looking at you i think 😂", time: "8:41 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i feel targeted", time: "8:42 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "writing so fast rn. he's dropping these one after another. blessed this blessed that. it's like a whole new rulebook.", time: "8:43 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "\"blessed are those who are persecuted\" is an INTERESTING flex", time: "8:44 AM" },
  { sender: "Philip", color: "#C084FC", msg: "ok new section. he just said we're the salt of the earth.", time: "8:48 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "salt?", time: "8:48 AM" },
  { sender: "Philip", color: "#C084FC", msg: "and also the light of the world", time: "8:49 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "are we salt or light. we can't be both. those are different substances.", time: "8:49 AM" },
  { sender: "John", color: "#34D399", msg: "it's a METAPHOR thomas", time: "8:50 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "metaphors should be internally consistent john", time: "8:50 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "OK WAIT. he just said \"if anyone slaps you on the right cheek, turn to them the other cheek also\"", time: "9:02 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "HE SAID WHAT", time: "9:02 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "turn the other cheek simon", time: "9:03 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "if someone slaps me they are getting slapped BACK. that's just physics. equal and opposite reaction.", time: "9:03 AM" },
  { sender: "James", color: "#2DD4BF", msg: "that's not physics simon that's just fighting", time: "9:04 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "simon is having a real rough sermon 😂", time: "9:04 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he also said love your ENEMIES. LOVE them. my whole personality is hating my enemies.", time: "9:05 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "sounds like a you problem simon", time: "9:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "now he's talking about prayer. says don't do it for show. go in your room and close the door.", time: "9:12 AM" },
  { sender: "Philip", color: "#C084FC", msg: "pharisees in the crowd are lowkey fuming rn. they LOVE public prayer. that's their whole thing.", time: "9:13 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's teaching a prayer now. \"Our Father in heaven, hallowed be your name...\"", time: "9:14 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "everyone slow down i'm trying to get this word for word", time: "9:14 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "\"give us today our daily bread\" ok but what about savings? long term planning? this feels fiscally irresponsible.", time: "9:15 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "THANK you thomas. as treasurer i've been thinking the same thing.", time: "9:15 AM" },
  { sender: "John", color: "#34D399", msg: "the treasurer and the skeptic agreeing on something. this is a dark timeline.", time: "9:16 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "OH. he just said \"do not store up treasures on earth\" and \"you cannot serve both God and money\" 💀", time: "9:22 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i'm choosing not to hear that", time: "9:22 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "that one's going in the book underlined judas", time: "9:23 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"why do you look at the speck of sawdust in your brother's eye and pay no attention to the PLANK in your own eye\" 😭😭", time: "9:30 AM" },
  { sender: "James", color: "#2DD4BF", msg: "A PLANK 💀 not a stick. not a twig. a full PLANK of wood in your eye. he's so dramatic i love him.", time: "9:31 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "everyone just looked at each other after that one lol", time: "9:31 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas you just touched your eye 😂", time: "9:32 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i had something in it. unrelated.", time: "9:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"do not worry about tomorrow, for tomorrow will worry about itself. each day has enough trouble of its own.\"", time: "9:40 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "that is the exact OPPOSITE of planning. tomorrow is the ONLY thing you should worry about. that's what planning IS.", time: "9:41 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas is going to need a separate debrief after this sermon", time: "9:41 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i will need several.", time: "9:42 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "i've been quiet but i just want to say this is the greatest thing i've ever heard in my life. every sentence is hitting.", time: "9:45 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "every sentence is hitting ME. personally. in the face. which i'm apparently supposed to just accept.", time: "9:46 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's wrapping up. something about building your house on rock vs sand.", time: "9:52 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "FINALLY something practical. rock foundations are superior to sand. this is just engineering.", time: "9:53 AM" },
  { sender: "John", color: "#34D399", msg: "thomas it's ANOTHER metaphor", time: "9:53 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "oh", time: "9:53 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he thought Jesus was doing a construction seminar 💀", time: "9:54 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's done. he just stopped speaking. the crowd is SILENT.", time: "9:56 AM" },
  { sender: "John", color: "#34D399", msg: "nobody is moving. i think some people are crying.", time: "9:56 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "my hand is CRAMPING but i got most of it. this is the most important thing i've ever written down.", time: "9:57 AM" },
  { sender: "Philip", color: "#C084FC", msg: "people are whispering that he teaches \"as one who has authority, not as the scribes.\" which is lowkey the biggest burn on the scribes i've ever heard.", time: "9:58 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "so quick recap he basically said: be humble, be merciful, be pure, make peace, expect persecution, don't show off, don't worry, don't judge, love everyone including your enemies, pray simply, and build your life on his words. in like 90 minutes.", time: "9:59 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "and he personally victimized me at least four times", time: "10:00 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i understood about 60% of that and i have follow up questions on all of it", time: "10:00 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "only 60%? honestly same.", time: "10:01 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i think we're all going to be unpacking this one for a while", time: "10:02 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "years. we will be unpacking this for years.", time: "10:02 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i was actually HERE for this one and it was incredible. also simon's face during \"love your enemies\" was the funniest thing i've ever seen in person. 💅", time: "10:05 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i'm working on it ok. i'm WORKING on it.", time: "10:05 AM" },
  { type: "system", text: "Read by everyone" },
],
});
