// Episode: Quiet. Be Still.
// Scripture: Mark 4:35-41 · Matt 8:23-27 · Luke 8:22-25
window.EPISODES.push({
  id: "storm",
  title: "Quiet. Be Still.",
  subtitle: "He scolded the sky and went back to sleep",
  emoji: "⛈️😴🤫",
  location: "Sea of Galilee",
  scripture: "Mark 4:35-41 · Matt 8:23-27 · Luke 8:22-25",
  time: "9:30 PM",
  battery: 30,
  messages: [
  { type: "system", text: "Today, 7:20 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "beautiful evening on the lake. Jesus said let's cross to the other side. smooth water. nice breeze. vibes are immaculate.", time: "7:20 PM" },
  { sender: "John", color: "#34D399", msg: "golden hour on the sea of galilee is unmatched honestly", time: "7:21 PM" },
  { sender: "James", color: "#2DD4BF", msg: "Jesus is already asleep in the back of the boat on a cushion. man was TIRED.", time: "7:22 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he fell asleep in like 30 seconds. head on the cushion and OUT.", time: "7:22 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "good for him honestly. the man works hard. he deserves rest.", time: "7:23 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "it's very peaceful rn. just the sound of water and Jesus softly snoring.", time: "7:24 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "he snores?? 😂", time: "7:24 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "gently. it's a gentle snore. very holy.", time: "7:25 PM" },
  { sender: "Philip", color: "#C084FC", msg: "\"very holy snoring\" is going to live in my head forever matthew 😂", time: "7:25 PM" },
  { type: "system", text: "8:45 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "wind just picked up a little", time: "8:45 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "yeah i felt that too. nothing major. just a shift.", time: "8:46 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "i've been on this lake my whole life. it does this sometimes. no big deal.", time: "8:47 PM" },
  { type: "system", text: "9:10 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok it's getting a little choppier", time: "9:10 PM" },
  { sender: "James", color: "#2DD4BF", msg: "waves are picking up for sure", time: "9:11 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "still manageable. i've seen worse. probably.", time: "9:12 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "\"probably\" is doing a lot of work in that sentence peter", time: "9:12 PM" },
  { type: "system", text: "9:30 PM" },
  { sender: "Philip", color: "#C084FC", msg: "OK SO", time: "9:30 PM" },
  { sender: "Philip", color: "#C084FC", msg: "THIS IS NO LONGER A LITTLE CHOPPY", time: "9:30 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "waves are coming OVER THE SIDES now 😭", time: "9:31 PM" },
  { sender: "James", color: "#2DD4BF", msg: "there's water in the boat. actual water. inside the boat. where the water should NOT be.", time: "9:31 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok everyone stay calm. i've handled storms before. we just need to—", time: "9:32 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "PETER A WAVE JUST HIT ME IN THE FACE", time: "9:32 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok that's not ideal", time: "9:33 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "I CAN'T SEE ANYTHING. IT'S COMPLETELY DARK AND THE WIND IS SCREAMING.", time: "9:33 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the boat is ROCKING. like violently. i am holding onto the side with both hands.", time: "9:34 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i would like to formally state that i had concerns about this trip that were dismissed", time: "9:34 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "THOMAS NOT THE TIME", time: "9:35 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "is anyone else bailing water because i'm bailing water with my HANDS and it's not working", time: "9:35 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "the money bag is getting wet. if we lose the money bag i want that on the record.", time: "9:36 PM" },
  { sender: "James", color: "#2DD4BF", msg: "JUDAS WE ARE GOING TO DIE AND YOU'RE WORRIED ABOUT THE MONEY BAG", time: "9:36 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "if we survive we're going to need the money bag james. i'm thinking ahead.", time: "9:37 PM" },
  { sender: "Philip", color: "#C084FC", msg: "update the boat is now like 1/3 full of water. we are sinking. slowly but definitely sinking.", time: "9:38 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "HOW IS JESUS STILL ASLEEP 😭😭😭", time: "9:38 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "BRO IS KNOCKED OUT. the boat is getting destroyed and he's on a CUSHION taking a NAP.", time: "9:39 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the waves are taller than the boat now. i just want everyone to understand. the waves are TALLER than the BOAT.", time: "9:39 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "i have been on this lake for 20 years and this is the worst storm i have EVER seen. we are in actual danger.", time: "9:40 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "when the professional fisherman says we're in danger that means we are in DANGER", time: "9:40 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "I DON'T WANT TO DIE ON A BOAT. I'M NOT EVEN A FISHERMAN. I'M FROM INLAND.", time: "9:41 PM" },
  { sender: "James (son of Alphaeus)", color: "#6EE7B7", msg: "i'm going to be remembered as Little James who drowned. this is how it ends.", time: "9:41 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "if we die nobody will find my scrolls. my gospel goes down with us. this cannot happen.", time: "9:42 PM" },
  { sender: "Philip", color: "#C084FC", msg: "matthew is worried about his MANUSCRIPT while we're capsizing 💀", time: "9:42 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "IT'S IMPORTANT CONTENT PHILIP", time: "9:43 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "seriously HOW IS HE STILL SLEEPING. a wave just crashed over the entire boat and he didn't even FLINCH.", time: "9:44 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the man is sleeping through a category 5 hurricane on a cushion. that is elite-level napping. i'm terrified but also impressed.", time: "9:44 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i fought the roman empire and THIS is how i die. drowning. in a lake. while my rabbi sleeps. unbelievable.", time: "9:45 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok that's it. i'm waking him up. we're about to go under.", time: "9:46 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "FINALLY. yes. wake the man who can do miracles. this should have been step ONE.", time: "9:46 PM" },
  { sender: "John", color: "#34D399", msg: "peter just grabbed him and yelled \"TEACHER DON'T YOU CARE IF WE DROWN\"", time: "9:47 PM" },
  { sender: "James", color: "#2DD4BF", msg: "\"don't you care if we drown\" peter really went with guilt 😂", time: "9:47 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "in peter's defense we ARE drowning", time: "9:48 PM" },
  { sender: "John", color: "#34D399", msg: "he's waking up. he's looking around. he looks... annoyed?? like we interrupted his nap???", time: "9:48 PM" },
  { sender: "Philip", color: "#C084FC", msg: "WE'RE SINKING AND HE LOOKS INCONVENIENCED 😭", time: "9:49 PM" },
  { sender: "John", color: "#34D399", msg: "he's standing up in the boat", time: "9:49 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "standing?? the boat is rocking like crazy how is he STANDING", time: "9:50 PM" },
  { sender: "John", color: "#34D399", msg: "he just looked at the storm", time: "9:50 PM" },
  { sender: "John", color: "#34D399", msg: "and said", time: "9:50 PM" },
  { sender: "John", color: "#34D399", msg: "\"Quiet! Be still!\"", time: "9:50 PM" },
  { sender: "John", color: "#34D399", msg: "to the STORM. he talked to the WEATHER.", time: "9:51 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "guys", time: "9:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "no", time: "9:51 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the wind just stopped", time: "9:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "NO", time: "9:52 PM" },
  { sender: "James", color: "#2DD4BF", msg: "it's calm. the water is calm. like GLASS. in literally two seconds.", time: "9:52 PM" },
  { sender: "Philip", color: "#C084FC", msg: "WHAT JUST HAPPENED", time: "9:52 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "THE STORM LISTENED TO HIM. THE ACTUAL WEATHER OBEYED A VERBAL COMMAND.", time: "9:53 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "i went from screaming to dead silence in ONE SECOND. the whiplash. my body doesn't know what's happening.", time: "9:53 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "the wind. is gone. the waves. are gone. the lake is perfectly still. this violates every law of meteorology.", time: "9:54 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i can hear my own heartbeat. that's how quiet it is. five seconds ago the wind was screaming. now i can hear my HEARTBEAT.", time: "9:54 PM" },
  { sender: "John", color: "#34D399", msg: "he just looked at us and said \"Why are you so afraid? Do you still have no faith?\"", time: "9:55 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "WHY ARE WE SO AFRAID?? WE WERE SINKING. IN THE DARK. IN A HURRICANE. WHILE YOU NAPPED.", time: "9:56 PM" },
  { sender: "James", color: "#2DD4BF", msg: "he said \"still\" have no faith. STILL. like we should know better by now. we've been with him for months and we still panicked like it was day one.", time: "9:57 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "nobody is talking on the boat rn. everyone is just sitting in the water that's still sloshing around the bottom. soaking wet. staring at him. shook.", time: "9:58 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "someone just whispered \"who IS this? even the wind and the waves obey him.\" and honestly that's the only thought any of us can form rn.", time: "9:59 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i'm soaked. my robes are destroyed. there's water in my sandals. and i've never been more terrified. not of the storm. of HIM. of what he just did.", time: "10:00 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have no questions. i have only fear. i just watched a man scold the sky and the sky LISTENED.", time: "10:01 PM" },
  { sender: "Philip", color: "#C084FC", msg: "\"scold the sky\" is insane but also perfectly accurate 😭", time: "10:01 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "the stars are out now btw. completely clear sky. like the storm never happened. if i wasn't soaking wet i'd think i dreamed it.", time: "10:02 PM" },
  { sender: "Nathanael", color: "#FB923C", msg: "he's laying back down on the cushion. HE'S GOING BACK TO SLEEP.", time: "10:03 PM" },
  { sender: "James", color: "#2DD4BF", msg: "GOING BACK TO SLEEP 💀💀💀💀💀", time: "10:03 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "man stopped a hurricane and said \"anyway\" and went back to bed. that is the most unhinged power move in history.", time: "10:04 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "we're all sitting in 6 inches of water too scared to speak and he's NAPPING AGAIN. on the same cushion. same position. like absolutely nothing happened.", time: "10:05 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "\"do you still have no faith\" is going to haunt me forever btw. we've watched him heal people. multiply bread. cast out demons. and the FIRST sign of danger we panicked and screamed at him for sleeping. he's right. we should've known.", time: "10:07 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "the money bag survived btw. in case anyone was wondering.", time: "10:08 PM" },
  { sender: "James", color: "#2DD4BF", msg: "nobody was wondering judas", time: "10:08 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i am going to be processing this for the rest of my life. the ocean had a tantrum and he put it in timeout.", time: "10:10 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "so the sea tried to kill you, Jesus slept through it, you woke him up crying, he told the weather to shut up and it DID, then he went back to sleep?? and i wasn't invited on this boat trip?? the FOMO is devastating. 💅", time: "10:15 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "trust me mary you did NOT want to be on this boat", time: "10:15 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "also peter is still sitting in 6 inches of water and has not moved. none of us have moved. we might sit here until morning.", time: "10:16 PM" },
  { type: "system", text: "Read by everyone" },
],
});
