// Episode: Feeding of the 5,000
// Scripture: Matt 14:13-21 · Mark 6:30-44 · John 6:1-15
window.EPISODES.push({
  id: "feeding",
  title: "Feeding of the 5,000",
  subtitle: "A child's lunchbox at a famine",
  emoji: "🐟🍞",
  location: "Near Bethsaida",
  scripture: "Matt 14:13-21 · Mark 6:30-44 · John 6:1-15",
  time: "11:23 AM",
  battery: 70,
  messages: [
  { type: "system", text: "Today, 11:23 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "alright boys we are officially on PTO. Jesus said we're taking the boat to a quiet place to rest 🙌", time: "11:23 AM" },
  { sender: "John", color: "#34D399", msg: "FINALLY. i am so burnt out. we've been healing people nonstop for like three weeks", time: "11:24 AM" },
  { sender: "James", color: "#2DD4BF", msg: "i'm going to nap SO hard on this boat", time: "11:24 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "do we have snacks for the boat", time: "11:25 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "we have budget for snacks but let's be reasonable", time: "11:25 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "do we even know if this \"quiet place\" is actually quiet? has anyone verified this?", time: "11:26 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "thomas i beg you to just enjoy one thing without a risk assessment", time: "11:26 AM" },
  { type: "system", text: "12:47 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok so", time: "12:47 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "slight problem", time: "12:47 PM" },
  { sender: "John", color: "#34D399", msg: "what", time: "12:48 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "you know how we took the boat to get away from everyone", time: "12:48 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "they RAN here. on foot. they beat us here. there's THOUSANDS of them.", time: "12:48 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "I'M LOOKING AT THIS RN AND THERE'S NO WAY THAT'S NOT 5,000 PEOPLE 😭", time: "12:49 PM" },
  { sender: "James", color: "#2DD4BF", msg: "so much for PTO", time: "12:49 PM" },
  { sender: "Philip", color: "#C084FC", msg: "how did they even know where we were going 💀", time: "12:50 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "bro someone is ALWAYS snitching our location", time: "12:50 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "Find My Messiah app going crazy rn", time: "12:51 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "😂😂😂", time: "12:51 PM" },
  { sender: "John", color: "#34D399", msg: "what's Jesus doing", time: "12:52 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he looked at the crowd and immediately started teaching them. he said he felt compassion because they were \"like sheep without a shepherd\"", time: "12:52 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i mean that's sweet and all but our reservation at the quiet place is lowkey ruined", time: "12:53 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "there was no reservation thomas. it's a hillside.", time: "12:53 PM" },
  { type: "system", text: "4:38 PM" },
  { sender: "Philip", color: "#C084FC", msg: "guys it's getting late and nobody has eaten. this is about to be a PROBLEM.", time: "4:38 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "5,000 men plus women and kids so we're talking maybe 15,000 people with no food", time: "4:39 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "we should tell Jesus to send them to the villages to buy food right?", time: "4:39 PM" },
  { sender: "John", color: "#34D399", msg: "yeah that's the responsible thing. we're in the middle of nowhere.", time: "4:40 PM" },
  { sender: "Philip", color: "#C084FC", msg: "just told him", time: "4:42 PM" },
  { sender: "Philip", color: "#C084FC", msg: "he said \"you give them something to eat\" 😐", time: "4:42 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "i'm sorry WHAT", time: "4:43 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "with WHAT money?? that would cost like 200 denarii. that's 8 MONTHS of wages. we don't have that.", time: "4:43 PM" },
  { sender: "Philip", color: "#C084FC", msg: "that's literally what i said 😭 he just looked at me", time: "4:44 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok so we're all in agreement that feeding 15,000 people is logistically impossible right? just want to make sure i'm not the only one being rational here", time: "4:44 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "for once thomas is spitting", time: "4:45 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "screenshot that. i want it framed.", time: "4:45 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's saying go see what food we have. everyone check.", time: "4:47 PM" },
  { sender: "James", color: "#2DD4BF", msg: "i got nothing", time: "4:48 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "nothing", time: "4:48 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "empty handed 🤷‍♂️", time: "4:48 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "nope", time: "4:48 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "ok so", time: "4:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "i found a kid", time: "4:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he has five loaves of bread and two fish", time: "4:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "but like. what is that among so many people lol", time: "4:52 PM" },
  { sender: "Philip", color: "#C084FC", msg: "andrew you brought a child's lunchbox to a famine 💀💀💀", time: "4:52 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "five loaves. two fish. fifteen thousand mouths. the math is not mathing.", time: "4:53 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus said bring it to him and have everyone sit down in groups", time: "4:55 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "sit down in groups to eat WHAT exactly", time: "4:55 PM" },
  { sender: "John", color: "#34D399", msg: "thomas. brother. maybe just wait and see for once in your life.", time: "4:56 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i am simply asking questions 🙃", time: "4:56 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's blessing the bread rn. looking up to heaven. breaking it.", time: "4:58 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's handing us pieces to distribute", time: "4:58 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "wait", time: "4:59 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "WAIT", time: "4:59 PM" },
  { sender: "John", color: "#34D399", msg: "BRO", time: "4:59 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "IT'S NOT RUNNING OUT???", time: "5:00 PM" },
  { sender: "James", color: "#2DD4BF", msg: "I KEEP BREAKING OFF PIECES AND THERE'S MORE 😭😭😭", time: "5:00 PM" },
  { sender: "Philip", color: "#C084FC", msg: "i'm literally handing out fish and it just KEEPS COMING. this is unhinged. this is the most unhinged thing i've ever seen.", time: "5:01 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "the FISH TOO??? THE FISH TOO???", time: "5:01 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "everyone around me is eating. like EATING eating. they are full. from the kid's lunchbox.", time: "5:02 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i've been handing out bread for ten minutes and my basket is somehow heavier than when i started 😭", time: "5:03 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "the vibes out here are IMMACULATE rn. people are just sitting on the grass eating free bread in the sunset. this is lowkey a music festival without the music", time: "5:04 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok", time: "5:05 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have questions", time: "5:05 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "THOMAS", time: "5:05 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "NO HEAR ME OUT. where is the bread COMING from. like molecularly. is it multiplying? duplicating? is it new bread? is it the same bread but more? i need someone to explain the physics of this.", time: "5:06 PM" },
  { sender: "John", color: "#34D399", msg: "it's a MIRACLE thomas there are no physics", time: "5:06 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "everything has physics john", time: "5:07 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "i cannot even calculate the cost savings rn. this is financially unprecedented.", time: "5:07 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "judas is watching a miracle and doing accounting in his head 💀", time: "5:08 PM" },
  { type: "system", text: "5:34 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "everyone's eaten. everyone's full. Jesus says to collect the leftovers.", time: "5:34 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "there are LEFTOVERS.", time: "5:34 PM" },
  { sender: "James", color: "#2DD4BF", msg: "update: we collected the leftovers", time: "5:48 PM" },
  { sender: "James", color: "#2DD4BF", msg: "TWELVE BASKETS FULL", time: "5:48 PM" },
  { sender: "Philip", color: "#C084FC", msg: "we started with five loaves and two fish and ended with TWELVE BASKETS OF LEFTOVERS. he generated a 240,000% ROI on a child's lunch. i am going to pass out.", time: "5:49 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "writing this ALL down. every word. this chapter is going to go crazy.", time: "5:50 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "shoutout to the kid btw. that boy did NOT have to share his lunch and he did anyway. absolute legend.", time: "5:50 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "someone get that kid's name for the book", time: "5:51 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "i didn't get it 😬", time: "5:51 PM" },
  { sender: "John", color: "#34D399", msg: "i didn't either", time: "5:51 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "…none of us got his name??", time: "5:52 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "we had 12 guys and not ONE of us got the kid's name 💀", time: "5:52 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "this is exactly the kind of documentation failure i keep warning about", time: "5:53 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "thomas i will put you in a basket", time: "5:53 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "so we're just gonna call him \"a boy\" in the writeup huh", time: "5:54 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "i mean yeah basically", time: "5:54 PM" },
  { sender: "John", color: "#34D399", msg: "\"a boy\" is giving main character with zero credit. poor kid fr", time: "5:55 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok but can we circle back to the fact that we just watched bread multiply in real time and we're worried about a name", time: "5:56 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i'm worried about BOTH peter. some of us can multitask.", time: "5:56 PM" },
  { sender: "James", color: "#2DD4BF", msg: "i'm taking one of these leftover baskets home btw. calling dibs.", time: "5:57 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "those baskets are communal property james", time: "5:57 PM" },
  { sender: "James", color: "#2DD4BF", msg: "it's literally infinite bread judas let it go", time: "5:58 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "just catching up on this chat. 97 messages. y'all watched him multiply bread and fish for 15,000 people and half this thread is you arguing. absolutely iconic. never change. 💅", time: "6:02 PM" },
  { type: "system", text: "Read by everyone" },
],
});
