// Episode: Peter's 3-Second Career
// Scripture: Matt 14:22-33 · Mark 6:45-52 · John 6:16-21
window.EPISODES.push({
  id: "water",
  title: "Peter's 3-Second Career",
  subtitle: "As a water walker",
  emoji: "🌊🚶‍♂️",
  location: "Sea of Galilee",
  scripture: "Matt 14:22-33 · Mark 6:45-52 · John 6:16-21",
  time: "3:14 AM",
  battery: 25,
  messages: [
  { type: "system", text: "Today, 6:45 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok Jesus said to take the boat across the lake without him. he's staying behind to pray.", time: "6:45 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "by ourselves? at night? on the sea of galilee? in a boat?", time: "6:46 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas it's a lake. we've done this a thousand times.", time: "6:46 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i'm just flagging the risk factors", time: "6:47 PM" },
  { sender: "James", color: "#2DD4BF", msg: "peter you and andrew literally grew up on this lake lol we're fine", time: "6:47 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "exactly. i could sail this blindfolded. everyone relax.", time: "6:48 PM" },
  { type: "system", text: "9:30 PM" },
  { sender: "Philip", color: "#C084FC", msg: "ok so the wind picked up", time: "9:30 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "\"picked up\" is generous. it's HOWLING.", time: "9:31 PM" },
  { sender: "James", color: "#2DD4BF", msg: "we've been rowing for three hours and i'm pretty sure we've gone nowhere 😭", time: "9:32 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok it's a little choppy but i've seen worse", time: "9:33 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "peter a wave just went OVER the boat", time: "9:33 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "that's normal", time: "9:34 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "that is not normal peter", time: "9:34 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "i'm going to be sick. not emotionally. physically. right now.", time: "9:35 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i would like to get off this ride please", time: "9:35 PM" },
  { sender: "Judas", color: "#94A3B8", msg: "is it too late to swim back", time: "9:36 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "oh so NOW we acknowledge the risk factors", time: "9:36 PM" },
  { type: "system", text: "3:14 AM" },
  { sender: "Philip", color: "#C084FC", msg: "it's been SIX HOURS. my arms are going to fall off.", time: "3:14 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "why is it still windy. who did we upset.", time: "3:15 AM" },
  { sender: "John", color: "#34D399", msg: "this would be a great time for Jesus to be here just saying", time: "3:15 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "um", time: "3:18 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "guys", time: "3:18 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "there's something on the water", time: "3:18 AM" },
  { sender: "James", color: "#2DD4BF", msg: "WHAT", time: "3:19 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "THERE IS A FIGURE. WALKING. ON THE WATER. TOWARD US.", time: "3:19 AM" },
  { sender: "Philip", color: "#C084FC", msg: "IT'S A GHOST 👻😭😭😭", time: "3:19 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "WE'RE GONNA DIE", time: "3:19 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "absolutely NOT. i did NOT survive six hours of rowing to be taken out by a SEA GHOST", time: "3:20 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i'm not proud of the noise i just made", time: "3:20 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "multiple grown men are screaming rn. for the record. including me.", time: "3:20 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "can ghosts swim because if so we're cooked", time: "3:21 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ghosts don't swim judas. they don't have mass. that's basic ghost physics.", time: "3:21 AM" },
  { sender: "James", color: "#2DD4BF", msg: "THERE IS NO SUCH THING AS GHOST PHYSICS THOMAS", time: "3:21 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "EVERYONE SHUT UP", time: "3:22 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "it's talking", time: "3:22 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "it said \"Take courage! It is I. Don't be afraid.\"", time: "3:22 AM" },
  { sender: "John", color: "#34D399", msg: "wait. is that JESUS??", time: "3:23 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "WALKING??? ON THE LAKE???", time: "3:23 AM" },
  { sender: "James", color: "#2DD4BF", msg: "like ON TOP of the water?? like the water is FLOOR to him rn??", time: "3:23 AM" },
  { sender: "John", color: "#34D399", msg: "yes james. that is what walking on water means.", time: "3:24 AM" },
  { sender: "Philip", color: "#C084FC", msg: "ok so it's NOT a ghost it's just our rabbi casually strolling across a lake at 3 AM in a storm. totally normal. cool cool cool.", time: "3:24 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i just yelled \"LORD IF IT'S YOU TELL ME TO COME TO YOU ON THE WATER\"", time: "3:25 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "peter why would you say that", time: "3:25 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "peter NO", time: "3:25 AM" },
  { sender: "John", color: "#34D399", msg: "PETER WHAT ARE YOU DOING", time: "3:25 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "HE SAID COME", time: "3:26 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i'm going", time: "3:26 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "HE'S GETTING OUT OF THE BOAT", time: "3:26 AM" },
  { sender: "James", color: "#2DD4BF", msg: "THIS MAN IS GETTING OUT OF THE BOAT IN THE MIDDLE OF A STORM", time: "3:26 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "peter has lost his entire mind", time: "3:27 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "that's my brother btw. we were raised the same. i don't know what happened.", time: "3:27 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "HE'S STANDING ON THE WATER", time: "3:27 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "PETER IS STANDING ON THE WATER", time: "3:27 AM" },
  { sender: "Philip", color: "#C084FC", msg: "WHAT", time: "3:28 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "NO WAY NO WAY NO WAY", time: "3:28 AM" },
  { sender: "John", color: "#34D399", msg: "HE'S WALKING. HE'S ACTUALLY WALKING TOWARD JESUS ON THE WATER. I'M WATCHING THIS WITH MY OWN EYES.", time: "3:28 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the absolute AUDACITY of this man 😭😭", time: "3:28 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok i have to admit this is incredible. full credit to peter. i would never.", time: "3:29 AM" },
  { sender: "James", color: "#2DD4BF", msg: "wait", time: "3:29 AM" },
  { sender: "James", color: "#2DD4BF", msg: "wait wait wait", time: "3:29 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he's looking at the waves", time: "3:30 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "peter don't look down don't look down don't look down", time: "3:30 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "he looked down", time: "3:30 AM" },
  { sender: "John", color: "#34D399", msg: "HE'S SINKING 😭😭😭", time: "3:30 AM" },
  { sender: "Philip", color: "#C084FC", msg: "LMAOOOOO", time: "3:30 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "THE MANS HAD A TWO SECOND CAREER AS A WATER WALKER 💀💀💀", time: "3:31 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he's yelling \"LORD SAVE ME\" while going under. this is the worst and best thing i've ever witnessed.", time: "3:31 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "give him credit he DID walk on water for like 6 steps", time: "3:31 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "6 steps is 6 more than any of us would have done to be fair", time: "3:32 AM" },
  { sender: "James", color: "#2DD4BF", msg: "Jesus grabbed his hand and pulled him up. they're walking back together. peter looks SOAKED and HUMBLED.", time: "3:32 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "Jesus said \"You of little faith, why did you doubt?\" and peter is just standing there dripping. incredible cinema.", time: "3:33 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "he went from walking on water to dog paddling in 0.3 seconds. that has to be the fastest fall from grace in history.", time: "3:33 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "the emotional range of this boat ride has been staggering", time: "3:34 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok i'm back in the boat", time: "3:36 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i don't want to talk about it", time: "3:36 AM" },
  { sender: "James", color: "#2DD4BF", msg: "peter you HAVE to talk about it. you walked on water and then sank like a brick.", time: "3:36 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "I WALKED ON WATER THO. that's the headline. i walked on water.", time: "3:37 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the headline is you sank peter", time: "3:37 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "THE HEADLINE IS I WALKED", time: "3:37 AM" },
  { sender: "Philip", color: "#C084FC", msg: "it's really both headlines 😂", time: "3:38 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "\"Local Fisherman Walks On Water For 3 Seconds, Immediately Eats It\" is the headline and you know it", time: "3:38 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "bartholomew i will throw you off this boat", time: "3:38 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "at least you know he won't walk to safety 😂", time: "3:39 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "THOMAS", time: "3:39 AM" },
  { sender: "John", color: "#34D399", msg: "for real though. Jesus stepped into the boat and the wind IMMEDIATELY stopped. like someone turned off a fan. dead calm.", time: "3:40 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the silence right now is unreal. nobody is speaking. everyone is just staring at him.", time: "3:41 AM" },
  { sender: "John", color: "#34D399", msg: "he's truly the Son of God. i've never been more sure of anything.", time: "3:42 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i want to say something skeptical but honestly i just watched a man use the ocean as a sidewalk so i'm going to sit this one out", time: "3:43 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas sitting one out?? peter walking on water?? what timeline are we in", time: "3:44 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok final thoughts. yes i sank. but i also WALKED ON WATER. i am choosing to focus on the walking part. that is my personal brand now. i am a water walker.", time: "3:46 AM" },
  { sender: "James", color: "#2DD4BF", msg: "you are a water sinker peter", time: "3:46 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "WALKER", time: "3:46 AM" },
  { sender: "James", color: "#2DD4BF", msg: "sinker", time: "3:47 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "WALKER", time: "3:47 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "splasher", time: "3:47 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i hate this group chat", time: "3:48 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "just woke up to 84 messages. so Jesus walked on water, peter tried it and ate it after 3 seconds, and now he's rebranding as a \"water walker\"?? i'm going back to sleep this is too much. 💅", time: "3:52 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "IT WAS MORE THAN 3 SECONDS MARY", time: "3:52 AM" },
  { type: "system", text: "Read by everyone" },
],
});
