// Episode: The Lost Trilogy
// Scripture: Luke 15:1-32
window.EPISODES.push({
  id: "luke15",
  title: "The Lost Trilogy",
  subtitle: "Three parables, increasing emotional damage",
  emoji: "🐑🪙👨‍👦",
  location: "Luke 15",
  scripture: "Luke 15:1-32",
  time: "10:15 AM",
  battery: 70,
  messages: [
  { type: "system", text: "Today, 10:15 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "pharisees and scribes are grumbling again. they're mad that Jesus is eating with tax collectors and sinners. the usual.", time: "10:15 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "they're ALWAYS grumbling. it's their spiritual gift.", time: "10:16 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus heard them. he's turning around. i think he's about to respond.", time: "10:17 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "oh he's telling a parable. here we go.", time: "10:17 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "everyone focus. these always sound simple and then you're up at 2 AM thinking about them.", time: "10:18 AM" },
  { type: "system", text: "📖 Parable #1: The Lost Sheep" },
  { sender: "Peter", color: "#60A5FA", msg: "ok so. a shepherd has 100 sheep. he loses one. he leaves the 99 to go find the one.", time: "10:20 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "he leaves the 99?? UNATTENDED??", time: "10:20 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "that's. that's a lot of unsupervised sheep thomas is right", time: "10:21 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "from a risk management perspective you've now endangered 99 sheep to find 1. that's a 99% exposure rate.", time: "10:21 AM" },
  { sender: "James", color: "#2DD4BF", msg: "thomas it's a PARABLE not a business case", time: "10:22 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "actually thomas has a point. one sheep is what, maybe 3-4 denarii? the 99 are worth significantly more. the math doesn't math.", time: "10:22 AM" },
  { sender: "John", color: "#34D399", msg: "you two are missing the POINT", time: "10:23 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he finds the sheep, puts it on his shoulders, goes home, and throws a party. says there's more rejoicing in heaven over one sinner who repents than 99 righteous people.", time: "10:24 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "ok that's actually beautiful. the pharisees are the 99 who think they don't need saving. the sinners are the one. i get it.", time: "10:25 AM" },
  { sender: "Philip", color: "#C084FC", msg: "the pharisees' faces rn 😂 they did NOT like being called the 99 who don't matter as much", time: "10:25 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i understand the metaphor. i just think the shepherd should have delegated.", time: "10:26 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's starting another one", time: "10:27 AM" },
  { sender: "James", color: "#2DD4BF", msg: "there's MORE?", time: "10:27 AM" },
  { type: "system", text: "📖 Parable #2: The Lost Coin" },
  { sender: "Peter", color: "#60A5FA", msg: "a woman has 10 silver coins. she loses one. she lights a lamp, sweeps the entire house, searches carefully until she finds it.", time: "10:29 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "wait is this the same story", time: "10:29 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "it's... the same story but with a coin", time: "10:30 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "oh NOW i'm listening. money is involved.", time: "10:30 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "judas you are so predictable 😂", time: "10:31 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "is he going to tell the sheep story in every possible format. lost sheep. lost coin. what's next. lost sandal?", time: "10:31 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "she finds the coin and calls her friends and neighbors to celebrate.", time: "10:32 AM" },
  { sender: "James", color: "#2DD4BF", msg: "she threw a PARTY?? for ONE coin?? the party costs more than the coin.", time: "10:32 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "EXACTLY. the ROI on that celebration is negative. she's net down after the party.", time: "10:33 AM" },
  { sender: "Philip", color: "#C084FC", msg: "judas analyzing the financial viability of a parable about God's love is peak judas", time: "10:33 AM" },
  { sender: "John", color: "#34D399", msg: "it's the same point as the sheep. heaven rejoices over one repentant sinner. he's saying it twice because the pharisees didn't get it the first time.", time: "10:34 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "bold of him to assume they'll get it the second time", time: "10:34 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's still going. there's ANOTHER one.", time: "10:36 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "a THIRD??", time: "10:36 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "called it. lost sandal incoming.", time: "10:37 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "this is a trilogy now. the lost cinematic universe.", time: "10:37 AM" },
  { type: "system", text: "📖 Parable #3: The Prodigal Son" },
  { sender: "Peter", color: "#60A5FA", msg: "ok this one's different. it's longer. a man has two sons.", time: "10:38 AM" },
  { sender: "James", color: "#2DD4BF", msg: "oh we've upgraded from sheep and coins to PEOPLE. stakes are escalating.", time: "10:38 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the younger son goes to his father and says \"give me my share of the inheritance.\" NOW. while the father is still alive.", time: "10:39 AM" },
  { sender: "John", color: "#34D399", msg: "😳😳😳", time: "10:39 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "that's basically saying \"i wish you were dead\" to his dad's FACE. that's the most disrespectful thing i've ever heard.", time: "10:40 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "and the father GIVES it to him?? just hands it over??", time: "10:40 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "no reasonable father would do that. this parable is already unrealistic.", time: "10:41 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the son takes everything, goes to a distant country, and blows ALL of it on wild living.", time: "10:42 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "ALL of it?? no savings?? no investments?? nothing in a rainy day fund??", time: "10:42 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "judas the man is living in a parable not a financial planning seminar", time: "10:43 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "then a famine hits. he's broke. he gets a job feeding PIGS.", time: "10:44 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "PIGS. a jewish boy. feeding PIGS. that is rock bottom.", time: "10:44 AM" },
  { sender: "James", color: "#2DD4BF", msg: "actually rock bottom is the next part", time: "10:45 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's so hungry he wants to eat the pig food. the PODS THE PIGS ARE EATING.", time: "10:45 AM" },
  { sender: "Philip", color: "#C084FC", msg: "ok NOW that's rock bottom", time: "10:45 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "went from \"give me my inheritance\" to \"i want to eat pig slop\" in like 30 seconds of storytelling. Jesus does not mess around with character arcs.", time: "10:46 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the son comes to his senses. he rehearses a speech: \"Father I have sinned against heaven and against you. I am no longer worthy to be called your son. Make me like one of your hired servants.\"", time: "10:48 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "smart. realistic expectations. downgrade request. that's a reasonable negotiating position given the circumstances.", time: "10:48 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he heads home. BUT. while he's still a LONG WAY off, the father sees him and RUNS to him.", time: "10:50 AM" },
  { sender: "John", color: "#34D399", msg: "wait. the father RUNS??", time: "10:50 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "a wealthy patriarch. running. in public. with his robes. that is UNDIGNIFIED. men of his status do not run. ever.", time: "10:51 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the father throws his arms around him and KISSES him. the son starts his speech but the father cuts him off and yells to the servants — bring the best robe! a ring! sandals! kill the fattened calf! WE'RE HAVING A PARTY.", time: "10:52 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "HE DIDN'T EVEN LET HIM FINISH THE APOLOGY 😭", time: "10:52 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "the FATTENED CALF?? that's the one you save for the most important occasions. for the kid who blew his inheritance on partying??", time: "10:53 AM" },
  { sender: "James", color: "#2DD4BF", msg: "the ring. that's the family signet ring. he's not making him a servant. he's fully restoring him as a SON. immediately. no probation period.", time: "10:54 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "no probation?? no performance review?? no 90-day evaluation period?? this father has NO accountability systems.", time: "10:54 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas that is literally the point. it's GRACE.", time: "10:55 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "grace seems operationally risky but ok", time: "10:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "OK WAIT. there's a twist. the OLDER son.", time: "10:57 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he comes in from the field, hears the music and dancing, asks a servant what's going on, and finds out his brother is back and dad killed the fattened calf.", time: "10:58 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "and he is FURIOUS. refuses to go in.", time: "10:58 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "honestly? i get it.", time: "10:59 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i'm with the older brother on this one. he stayed. he worked. he was faithful. and THIS guy gets the party??", time: "10:59 AM" },
  { sender: "James", color: "#2DD4BF", msg: "ok hang on. the older brother says \"i've been slaving for you and you never even gave me a goat to celebrate with my friends. but this son of yours who devoured your wealth with prostitutes comes home and you kill the fattened calf??\"", time: "11:00 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he said \"this son of YOURS.\" not \"my brother.\" that's COLD.", time: "11:00 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "wait. wait wait wait. are the pharisees the older brother.", time: "11:01 AM" },
  { sender: "John", color: "#34D399", msg: "OH", time: "11:01 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "OH NO", time: "11:01 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the pharisees have been faithful. followed the rules. done everything right. and they're MAD that Jesus is celebrating with sinners. THEY'RE THE OLDER BROTHER.", time: "11:02 AM" },
  { sender: "Philip", color: "#C084FC", msg: "he just deconstructed the entire pharisee worldview with a FAMILY DINNER STORY", time: "11:02 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the father says \"Son, you are always with me, and everything I have is yours. But we had to celebrate because this brother of yours was dead and is alive. He was lost and is found.\"", time: "11:04 AM" },
  { sender: "John", color: "#34D399", msg: "\"this BROTHER of yours.\" the father corrected it. the older son said \"this son of yours\" and the father said no. he's your BROTHER. i'm actually shaking.", time: "11:05 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "ok i take back siding with the older brother. i just got wrecked.", time: "11:05 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the pharisees are standing there with their mouths open. some of them look like they've been punched.", time: "11:06 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "so let me get this straight. he told THREE stories. each one bigger than the last. sheep → coin → son. and all three were the same message: God will go to absurd lengths to recover what is lost. and anyone who has a problem with that IS the problem.", time: "11:07 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "thomas just summarized the whole thing perfectly and i'm not ok", time: "11:07 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "he spent 45 minutes telling the same story three ways with increasing emotional damage. this man is a WEAPON.", time: "11:08 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "still think the party cost more than the coin was worth but i understand that's not the takeaway", time: "11:09 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "growth from judas 😂", time: "11:09 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "\"was lost and is found.\" that's me. that's my whole story in six words. i will never get tired of hearing him say that. 💅😭", time: "11:12 AM" },
  { type: "system", text: "Read by everyone" },
],
});
