// Episode: Let He Who Is Without Sin
// Scripture: John 8:1-11
window.EPISODES.push({
  id: "stone",
  title: "Let He Who Is Without Sin",
  subtitle: "The woman caught in adultery",
  emoji: "✍️🪨",
  location: "The Temple Courts, Jerusalem",
  scripture: "John 8:1-11",
  time: "7:40 AM",
  battery: 75,
  messages: [
  { type: "system", text: "Today, 7:40 AM" },
  { sender: "John", color: "#34D399", msg: "Jesus is teaching in the temple courts again this morning. huge crowd. good energy.", time: "7:40 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "got my writing stuff. ready to document.", time: "7:41 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "beautiful morning for it. nothing could ruin th—", time: "7:42 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "oh no", time: "7:42 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "pharisees incoming. and scribes. a LOT of them.", time: "7:43 AM" },
  { sender: "James", color: "#2DD4BF", msg: "they're dragging a woman with them. she looks terrified.", time: "7:43 AM" },
  { sender: "John", color: "#34D399", msg: "they just threw her on the ground in front of Jesus. in front of EVERYONE. this is awful.", time: "7:44 AM" },
  { sender: "Philip", color: "#C084FC", msg: "they're saying she was caught in adultery and that the law of Moses says she should be stoned. they're asking Jesus what he thinks.", time: "7:45 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "this is a trap. if he says stone her, he contradicts his own teaching about mercy. if he says don't, they say he's breaking the law of Moses. they think they've got him.", time: "7:45 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "thomas is right. this is a setup. they don't care about this woman they're using her as a chess piece.", time: "7:46 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "also WHERE is the man?? adultery involves TWO people. they only brought the woman?? make it make sense.", time: "7:46 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "EXCELLENT point simon. where IS the guy.", time: "7:47 AM" },
  { sender: "James", color: "#2DD4BF", msg: "probably friends with one of the pharisees", time: "7:47 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok so Jesus isn't answering them", time: "7:48 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he bent down and he's... writing something. in the dirt. with his finger.", time: "7:48 AM" },
  { sender: "John", color: "#34D399", msg: "he's completely ignoring them 😂", time: "7:49 AM" },
  { sender: "Philip", color: "#C084FC", msg: "the pharisees look SO confused rn. they asked a theological question and he's doing arts and crafts on the ground.", time: "7:49 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what's he writing?? can anyone see??", time: "7:50 AM" },
  { sender: "James", color: "#2DD4BF", msg: "i can't read it from here", time: "7:50 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "i'm closer. it looks like... names? or words? i honestly can't tell.", time: "7:51 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "someone get closer and read it this could be critical information", time: "7:51 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "i'm not crawling on the ground in front of the pharisees thomas. YOU go.", time: "7:52 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the pharisees keep asking. they won't let it go. they're practically yelling at him now.", time: "7:53 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's standing up", time: "7:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "everyone just went quiet", time: "7:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he said \"Let any one of you who is without sin be the first to throw a stone at her.\"", time: "7:56 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "and then he bent back down and kept writing.", time: "7:56 AM" },
  { sender: "John", color: "#34D399", msg: "BRO.", time: "7:56 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "ABSOLUTE. SILENCE.", time: "7:57 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "that might be the hardest sentence anyone has ever said. in history. ever.", time: "7:57 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "he didn't break the law. he didn't contradict mercy. he just turned the whole thing back on them. that's... that's genius.", time: "7:58 AM" },
  { sender: "Philip", color: "#C084FC", msg: "nobody is moving. every pharisee is just standing there holding their stones looking at each other.", time: "7:58 AM" },
  { sender: "James", color: "#2DD4BF", msg: "you can literally WATCH them doing math in their heads rn. \"am i without sin? no. no i am not.\"", time: "7:59 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the old one in the front just dropped his stone", time: "8:00 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "HE'S WALKING AWAY 😂", time: "8:00 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "a second one just left. the one with the big beard.", time: "8:01 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "three more leaving now. they won't even make eye contact with anyone 💀", time: "8:01 AM" },
  { sender: "Philip", color: "#C084FC", msg: "they're leaving oldest first 😂😂😂 the older you are the more sins you've had time to collect. that's just math.", time: "8:02 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "the sound of stones dropping on dirt one by one is genuinely cinematic rn", time: "8:02 AM" },
  { sender: "James", color: "#2DD4BF", msg: "another one gone. he didn't even drop his stone he gently placed it down like he was ashamed of it 😭", time: "8:03 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "this is the most satisfying thing i've ever watched. the same guys who dragged this woman in here can't even stay in the room.", time: "8:03 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the last two just left. they practically RAN.", time: "8:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "every single one is gone. every one. the only people left are Jesus, the woman, and us.", time: "8:05 AM" },
  { sender: "John", color: "#34D399", msg: "he's still writing in the dirt btw. hasn't even looked up to watch them leave. king behavior.", time: "8:06 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "i am DESPERATE to know what he's writing", time: "8:06 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "we are going to debate what he wrote in that dirt for the rest of our lives and none of us will ever know", time: "8:07 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's standing up again. he's looking at the woman.", time: "8:08 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he said \"Woman, where are they? Has no one condemned you?\"", time: "8:08 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "she said \"No one, sir.\"", time: "8:09 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he said \"Then neither do I condemn you. Go now and leave your life of sin.\"", time: "8:09 AM" },
  { sender: "John", color: "#34D399", msg: "i'm done. i'm absolutely done.", time: "8:10 AM" },
  { sender: "Philip", color: "#C084FC", msg: "she's crying so hard she can barely stand up", time: "8:10 AM" },
  { sender: "James", color: "#2DD4BF", msg: "they dragged her in here to die and she's walking out free. i can't.", time: "8:11 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "he gave her mercy AND truth in the same breath. \"i don't condemn you\" AND \"leave your life of sin.\" both. at the same time. how does he do that.", time: "8:12 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he didn't excuse what she did. but he refused to let her be destroyed for it. that's... i don't have words for that.", time: "8:13 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "simon with no sarcasm? this moment really is special.", time: "8:13 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have zero questions. that was the clearest thing i've ever seen him do. the trap was perfect and he walked through it like it wasn't even there.", time: "8:14 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "two thomas moments of zero questions now. matthew are you tracking this?", time: "8:14 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "oh i'm tracking everything. this whole scene. every stone that dropped. this chapter writes itself.", time: "8:15 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "she's walking away. she keeps looking back at him like she can't believe she's alive. and he just went back to teaching like nothing happened.", time: "8:16 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i've been quiet this whole time but that was extraordinary. even i can admit that.", time: "8:17 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i watched the whole thing from the crowd. that woman's face when he said \"neither do I condemn you\" is something i will never forget. he sees people nobody else is willing to look at. that's why i follow him. 💔", time: "8:20 AM" },
  { sender: "John", color: "#34D399", msg: "❤️", time: "8:20 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "❤️", time: "8:21 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "❤️", time: "8:21 AM" },
  { type: "system", text: "Read by everyone" },
],
});
