// Episode: The Raising of Lazarus
// Scripture: John 11:1-44
window.EPISODES.push({
  id: "lazarus",
  title: "The Raising of Lazarus",
  subtitle: "Condolences → celebration in 90 minutes",
  emoji: "🪦➡️🫁",
  location: "Bethany",
  scripture: "John 11:1-44",
  time: "2:14 PM",
  battery: 60,
  messages: [
  { type: "system", text: "Tuesday, 2:14 PM" },
  { sender: "Martha", color: "#F472B6", msg: "hey everyone. Lazarus is really sick. like really really sick. we've sent word to Jesus but he's across the Jordan and i don't know how long it'll take to reach him.", time: "2:14 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "praying for him right now 🙏 Jesus will come. he loves Lazarus.", time: "2:16 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "the message reached us. Jesus said \"this sickness will not end in death\" so that's encouraging right?", time: "2:20 PM" },
  { sender: "Martha", color: "#F472B6", msg: "ok good. ok. thank you. please hurry.", time: "2:22 PM" },
  { sender: "John", color: "#34D399", msg: "we're praying for you guys ❤️", time: "2:25 PM" },
  { type: "system", text: "Wednesday, 9:41 AM" },
  { sender: "Mary (sister of Lazarus)", color: "#FB7185", msg: "any update on when Jesus is coming? Lazarus is worse.", time: "9:41 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "um. so. Jesus hasn't left yet.", time: "9:45 AM" },
  { sender: "Martha", color: "#F472B6", msg: "what do you mean he hasn't left yet", time: "9:45 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "i mean he's still here. he stayed.", time: "9:46 AM" },
  { sender: "Martha", color: "#F472B6", msg: "my brother is DYING", time: "9:46 AM" },
  { sender: "John", color: "#34D399", msg: "we don't understand it either Martha. we're sorry. he said it won't end in death so maybe he knows something we don't?", time: "9:48 AM" },
  { sender: "Mary (sister of Lazarus)", color: "#FB7185", msg: "i'm trying to trust that but it's really hard right now", time: "9:50 AM" },
  { type: "system", text: "Thursday, 6:12 AM" },
  { sender: "Martha", color: "#F472B6", msg: "Lazarus passed away in the night.", time: "6:12 AM" },
  { sender: "John", color: "#34D399", msg: "Martha i am so sorry 💔", time: "6:14 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "no. no no no.", time: "6:14 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i don't have words. i'm so sorry. we love you both so much. 💔", time: "6:15 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "rest in peace Lazarus. one of the kindest men i've ever known.", time: "6:16 AM" },
  { sender: "Philip", color: "#C084FC", msg: "heartbroken for you Martha and Mary 😢", time: "6:17 AM" },
  { sender: "James", color: "#2DD4BF", msg: "🕊️💔", time: "6:17 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i'm so sorry. truly.", time: "6:18 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "praying for your whole family 🙏", time: "6:19 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "this doesn't feel real 💔", time: "6:20 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "rest in peace brother 🕊️", time: "6:20 AM" },
  { sender: "Mary (sister of Lazarus)", color: "#FB7185", msg: "he kept asking if Jesus was coming. that was the last thing he asked about.", time: "6:22 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "i can't read that without crying. i'm so sorry.", time: "6:24 AM" },
  { sender: "Martha", color: "#F472B6", msg: "if he had been here my brother would not have died. i believe that with my whole heart.", time: "6:26 AM" },
  { type: "system", text: "Friday, 10:30 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "so update. Jesus just told us \"Lazarus has fallen asleep and I am going to wake him up\"", time: "10:30 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "wait so is that good? if he's sleeping maybe he's getting better?", time: "10:31 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "that's what we said", time: "10:31 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "then he looked at us and said \"Lazarus is dead.\"", time: "10:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "and then he said he's GLAD he wasn't there?? so that we may believe???", time: "10:32 AM" },
  { sender: "Philip", color: "#C084FC", msg: "i'm sorry he said WHAT", time: "10:33 AM" },
  { sender: "John", color: "#34D399", msg: "i don't understand what's happening but we're going to Bethany now", time: "10:33 AM" },
  { sender: "James", color: "#2DD4BF", msg: "isn't Bethany right next to Jerusalem? where they literally tried to stone us last time??", time: "10:34 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "yes. yes it is. we're probably going to die.", time: "10:35 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "but let's go so that we may die with him i guess 🫡", time: "10:35 AM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "thomas that is simultaneously the bravest and most dramatic thing you've ever said", time: "10:36 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i contain multitudes bartholomew", time: "10:36 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "Martha, Mary — we're on our way. Jesus is coming.", time: "10:38 AM" },
  { sender: "Martha", color: "#F472B6", msg: "it's been four days. but ok.", time: "10:40 AM" },
  { type: "system", text: "Saturday, 1:15 PM — Bethany" },
  { sender: "Andrew", color: "#FBBF24", msg: "we're almost there. there's a huge crowd of mourners at the house.", time: "1:15 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "Martha just came running out to meet Jesus on the road before he even got to the village", time: "1:18 PM" },
  { sender: "John", color: "#34D399", msg: "she said \"Lord if you had been here my brother would not have died.\" she's been holding that in for four days and you could hear it.", time: "1:19 PM" },
  { sender: "John", color: "#34D399", msg: "then she said \"but even now I know that God will give you whatever you ask.\" which is... wow. that's faith after four days of grief.", time: "1:20 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus told her \"Your brother will rise again\" and she said she knows, at the resurrection on the last day", time: "1:21 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "and then he said \"I am the resurrection and the life. whoever believes in me will live even though they die.\" and asked if she believed that.", time: "1:22 PM" },
  { sender: "Philip", color: "#C084FC", msg: "chills. full body chills.", time: "1:22 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "Mary just came out too. she fell at his feet saying the same thing. \"if you had been here he would not have died.\" she's sobbing.", time: "1:25 PM" },
  { sender: "John", color: "#34D399", msg: "guys", time: "1:26 PM" },
  { sender: "John", color: "#34D399", msg: "Jesus is crying.", time: "1:26 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "i've never seen him cry before", time: "1:27 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "the whole crowd is watching. some are saying \"see how he loved him.\" others are saying \"couldn't he have kept him from dying?\"", time: "1:28 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i mean... they're not wrong to ask that", time: "1:28 PM" },
  { sender: "James", color: "#2DD4BF", msg: "thomas. not now.", time: "1:29 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "fair. retracting.", time: "1:29 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's walking to the tomb", time: "1:32 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he just said \"take away the stone\"", time: "1:33 PM" },
  { sender: "Martha", color: "#F472B6", msg: "i literally just said \"Lord by this time there will be a bad smell, he's been dead four days\" out loud in front of everyone. someone had to be practical.", time: "1:34 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "martha really said \"i love you Jesus but it's gonna STINK in there\" 😭", time: "1:34 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "honestly someone had to say it", time: "1:35 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he said \"did I not tell you that if you believe you will see the glory of God?\"", time: "1:35 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "they're rolling the stone away", time: "1:36 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's praying. out loud. looking up.", time: "1:37 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "GUYS HE JUST SHOUTED \"LAZARUS COME OUT\"", time: "1:38 PM" },
  { sender: "John", color: "#34D399", msg: "everyone is dead silent", time: "1:38 PM" },
  { sender: "John", color: "#34D399", msg: "wait", time: "1:38 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "DO YOU SEE THAT", time: "1:39 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "SOMETHING IS MOVING IN THE TOMB", time: "1:39 PM" },
  { sender: "Philip", color: "#C084FC", msg: "no no no no no no", time: "1:39 PM" },
  { sender: "James", color: "#2DD4BF", msg: "HE'S WALKING OUT. HE IS WALKING OUT OF THE TOMB. WRAPPED IN BURIAL CLOTHS. HE IS ALIVE.", time: "1:40 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "I CAN'T BREATHE", time: "1:40 PM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i am on the GROUND rn. my legs gave out. this is not real.", time: "1:40 PM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "HE WAS DEAD. HE WAS DEAD FOR FOUR DAYS. I'M GOING TO THROW UP.", time: "1:41 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i", time: "1:41 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i have no questions.", time: "1:41 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "THOMAS HAS NO QUESTIONS. THE WORLD IS ENDING.", time: "1:42 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "Jesus said \"take off the grave clothes and let him go.\" people are SCREAMING and crying and falling on the ground.", time: "1:42 PM" },
  { sender: "Martha", color: "#F472B6", msg: "i can't type. i'm holding my brother. he's warm. he's breathing. he's alive.", time: "1:44 PM" },
  { sender: "Mary (sister of Lazarus)", color: "#FB7185", msg: "i will never doubt anything ever again for the rest of my life", time: "1:45 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i am a complete wreck reading this in real time. someone hold me.", time: "1:46 PM" },
  { sender: "John", color: "#34D399", msg: "\"I am the resurrection and the life.\" he wasn't speaking in metaphor. he meant it literally. i understand now.", time: "1:48 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "writing through tears. this is the chapter. this is THE chapter.", time: "1:50 PM" },
  { type: "system", text: "3:22 PM" },
  { type: "system", text: "Lazarus has joined the group" },
  { sender: "Peter", color: "#60A5FA", msg: "YO 😭😭😭", time: "3:23 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "THE LEGEND HIMSELF", time: "3:23 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "so i just scrolled up and read everything", time: "3:25 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "\"rest in peace Lazarus\" is crazy to read about yourself ngl 💀", time: "3:25 PM" },
  { sender: "James", color: "#2DD4BF", msg: "DID HE JUST USE THE SKULL EMOJI 💀💀💀", time: "3:26 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "i think i'm allowed", time: "3:26 PM" },
  { sender: "Philip", color: "#C084FC", msg: "he is absolutely allowed 😂", time: "3:27 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok i have ONE question. what was it like. being dead.", time: "3:28 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "THERE HE IS", time: "3:28 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "honestly? i heard his voice. that's the first thing i remember. it cut through everything like nothing else existed.", time: "3:30 PM" },
  { sender: "John", color: "#34D399", msg: "i should not be crying this hard at a group chat", time: "3:31 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "also lowkey embarrassing walking out wrapped head to toe in burial cloths in front of like 200 people. not my best look.", time: "3:32 PM" },
  { sender: "Andrew", color: "#FBBF24", msg: "bro came back from the dead and his first concern is the fit 😭", time: "3:32 PM" },
  { sender: "Martha", color: "#F472B6", msg: "i told them it was going to smell in there and i stand by that. i was being helpful.", time: "3:33 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "martha i was DEAD and you were worried about the smell. never change. 😂", time: "3:34 PM" },
  { sender: "Martha", color: "#F472B6", msg: "someone has to be the practical one in this family 🤷‍♀️", time: "3:34 PM" },
  { sender: "Mary (sister of Lazarus)", color: "#FB7185", msg: "i'm never letting go of your arm again btw. you're stuck with me forever now.", time: "3:35 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "that's fine. i'm not going anywhere. 🤍", time: "3:36 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "ok i'm a mess. this whole thread is going in the book. every single word.", time: "3:37 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "yo who sent \"rest in peace one of the kindest men i've ever known\" that was actually really sweet", time: "3:38 PM" },
  { sender: "Matthew", color: "#818CF8", msg: "that was me 😅", time: "3:38 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "matthew i'm framing that. even though it aged TERRIBLY. 😂", time: "3:39 PM" },
  { sender: "Thomas", color: "#A78BFA", msg: "all of our condolence messages aged terribly to be fair", time: "3:40 PM" },
  { sender: "Peter", color: "#60A5FA", msg: "\"rest in peace\" to a guy who's currently typing in the group chat is insane 💀", time: "3:40 PM" },
  { sender: "Lazarus", color: "#38BDF8", msg: "alright so what did i miss in the last four days. catch me up.", time: "3:42 PM" },
  { sender: "Bartholomew", color: "#FB923C", msg: "brother YOU are what happened in the last four days. there is no other news.", time: "3:42 PM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "the way this chat went from condolences to celebration in 90 minutes is the most unhinged emotional journey i have ever been on. 10/10 would read again. 💅", time: "3:45 PM" },
  { type: "system", text: "Read by everyone" },
],
});
