// Episode: The Tree That Had It Coming
// Scripture: Mark 11:12-25 · Matt 21:18-22
window.EPISODES.push({
  id: "figtree",
  title: "The Tree That Had It Coming",
  subtitle: "He was hungry. The tree had no figs. The tree is no longer with us.",
  emoji: "🌳😤💀",
  location: "Road from Bethany to Jerusalem",
  scripture: "Mark 11:12-25 · Matt 21:18-22",
  time: "7:45 AM",
  battery: 85,
  messages: [
  { type: "system", text: "Day 1 — 7:45 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "heading out of Bethany this morning. Jesus is up front. beautiful walk. everyone's in a good mood.", time: "7:45 AM" },
  { sender: "John", color: "#34D399", msg: "anyone eat breakfast? i didn't eat breakfast.", time: "7:46 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "same. we left early. my stomach is yelling at me.", time: "7:47 AM" },
  { sender: "James", color: "#2DD4BF", msg: "Jesus didn't eat either. he looks hungry.", time: "7:48 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "oh he's definitely hungry. he's got that look. the \"i need food immediately\" walk.", time: "7:48 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "we should have planned for this. a simple meal prep the night before would have prevented this entire situation.", time: "7:49 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas we were staying at someone's house. you can't meal prep at someone else's house.", time: "7:50 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "you absolutely can. it's called being prepared.", time: "7:50 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "wait. he's looking at something. off the road.", time: "7:52 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "it's a fig tree. big one. full of leaves.", time: "7:52 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "FIGS. yes. problem solved. let's go. 🎉", time: "7:53 AM" },
  { sender: "John", color: "#34D399", msg: "it's got tons of leaves so it should be loaded with fruit right?", time: "7:53 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he's walking over to it. man is on a MISSION for these figs.", time: "7:54 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the way he's speed-walking toward that tree is taking me out 😂 he's so hungry", time: "7:54 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's looking through the branches", time: "7:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "uh oh", time: "7:55 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "what", time: "7:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "nothing but leaves. there are NO figs on this tree. zero.", time: "7:56 AM" },
  { sender: "John", color: "#34D399", msg: "the tree catfished him 💀 all leaves no fruit", time: "7:56 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "well. technically it's not fig season yet. so the tree isn't really at fault here. it's a seasonal issue.", time: "7:57 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas don't bring logic into this he's HUNGRY", time: "7:57 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "guys. his face. he's looking at this tree like it personally offended him.", time: "7:58 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he's got the same face he had before he flipped the tables in the temple 😳", time: "7:58 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "is he about to fight a TREE", time: "7:59 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's talking to the tree.", time: "7:59 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "he's WHAT", time: "7:59 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he just said \"May no one ever eat fruit from you again.\"", time: "8:00 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "TO THE TREE. he cursed the tree. he looked at a fig tree and cursed it.", time: "8:00 AM" },
  { sender: "John", color: "#34D399", msg: "HE CURSED A TREE 😂😂😂😂", time: "8:00 AM" },
  { sender: "James", color: "#2DD4BF", msg: "THE SON OF GOD JUST BEEFED WITH PRODUCE 💀💀💀", time: "8:01 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the tree is standing there with all its leaves like 👁️🌿👁️ not knowing it just got eternally condemned", time: "8:01 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i want to reiterate. it is NOT fig season. the tree was not supposed to have figs right now. he cursed a tree for not doing something it biologically could not do yet.", time: "8:02 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas i don't think the tree's seasonal schedule is going to hold up as a defense rn 😂", time: "8:02 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "should i write this down. he cursed a fig tree. is this canon. is this going in the book.", time: "8:03 AM" },
  { sender: "John", color: "#34D399", msg: "you HAVE to write it down matthew. people need to know.", time: "8:03 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "we have seen him heal the blind. raise the dead. calm storms. and today he chose to use his power to curse a tree that didn't have snacks.", time: "8:04 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "\"didn't have snacks\" is WILD phrasing for a divine miracle but honestly accurate 😂", time: "8:05 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "he walked away from the tree like it owed him money btw. didn't look back. ice cold.", time: "8:05 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "could he not have just... made figs appear? he turned water into wine. he multiplied bread. but for figs he chose VIOLENCE??", time: "8:06 AM" },
  { sender: "James", color: "#2DD4BF", msg: "judas actually asking the real question for once 💀", time: "8:07 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "right?? he had OPTIONS. create figs. multiply existing figs from another tree. send someone to buy figs. but no. he cursed it. the tree got the death penalty for being out of season.", time: "8:07 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i'm not gonna lie i'm a little scared rn. if that's what happens to a TREE that disappoints him what happens to US 😅", time: "8:08 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "peter asking the questions we're all thinking but none of us want to say out loud 😂", time: "8:09 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "note to self: always have snacks when Jesus is around. ALWAYS.", time: "8:09 AM" },
  { sender: "Philip", color: "#C084FC", msg: "\"always have snacks\" is now a commandment apparently 😂", time: "8:10 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "he's already moved on btw. walking toward Jerusalem like nothing happened. we're all standing here processing and he's a quarter mile ahead.", time: "8:11 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the tree is just standing there. in the sun. with all its leaves. not knowing its fate has been sealed. this is lowkey tragic.", time: "8:12 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "do we think something will actually happen to the tree? or was it more of a... metaphorical curse? an expression of frustration?", time: "8:13 AM" },
  { sender: "John", color: "#34D399", msg: "thomas when has Jesus EVER said something he didn't mean", time: "8:13 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "fair. that tree is cooked.", time: "8:14 AM" },
  { type: "system", text: "Day 2 — 8:10 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "we're walking the same road as yesterday. passing the fig tree.", time: "8:10 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "guys", time: "8:10 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "GUYS", time: "8:11 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "WHAT", time: "8:11 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "THE FIG TREE IS DEAD", time: "8:11 AM" },
  { sender: "John", color: "#34D399", msg: "WHAT DO YOU MEAN DEAD", time: "8:12 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "WITHERED. FROM THE ROOTS. the whole thing. every branch. every leaf. completely dead. dried up. in ONE DAY.", time: "8:12 AM" },
  { sender: "James", color: "#2DD4BF", msg: "it was FULLY green yesterday. full leaves. big healthy tree. and now it looks like it's been dead for a YEAR.", time: "8:13 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the tree is GONE. like someone hit fast forward on decomposition. this is HORRIFYING.", time: "8:13 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "biologically this should not be possible. trees don't die overnight. root death takes weeks minimum. this defies botany.", time: "8:14 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas said it \"defies botany\" like that's going to stop the man who defies PHYSICS on a regular basis 😂", time: "8:14 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "i was half joking yesterday when we were all laughing about the tree curse. i am NOT laughing now. the tree is a skeleton.", time: "8:15 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he verbally dragged a tree and it DIED OF SHAME. that is the most savage thing i have ever witnessed.", time: "8:16 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i just said to Jesus \"Rabbi look! The fig tree you cursed has withered!\" and he didn't even seem surprised. like OF COURSE it did.", time: "8:17 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "he responded with \"Have faith in God. Truly I tell you, if anyone says to this mountain, 'Go, throw yourself into the sea,' and does not doubt in their heart but believes that what they say will happen, it will be done for them.\"", time: "8:18 AM" },
  { sender: "James", color: "#2DD4BF", msg: "so the fig tree was a LESSON?? this was never about figs?? he used a TREE as a TEACHING AID??", time: "8:19 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "wait. the tree with leaves but no fruit is a metaphor for people who LOOK faithful but produce nothing?? and the curse is what happens when you're all show and no substance?? that's aimed at the pharisees isn't it.", time: "8:20 AM" },
  { sender: "John", color: "#34D399", msg: "thomas just cracked the code. he cursed the tree the day before he went to the temple and called out the religious leaders. the tree IS the pharisees. all leaves no fruit.", time: "8:21 AM" },
  { sender: "Philip", color: "#C084FC", msg: "so we spent 24 hours laughing about him being hangry and the whole time it was a THEOLOGICAL STATEMENT?? 💀", time: "8:22 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he didn't beef with a tree. he performed a prophetic demonstration using a tree as the visual aid. and it worked because we will NEVER forget this.", time: "8:23 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he also said whatever you ask for in prayer, believe that you have received it, and it will be yours. so the lesson is faith. actual faith. not decorative faith. not fig-tree-looking-good-but-empty faith.", time: "8:24 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i will never look at a fig tree the same way again. every fig tree is now a pop quiz on whether i'm actually producing fruit or just looking leafy.", time: "8:25 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "ok so to summarize. he was hungry. saw a tree with no fruit. cursed it. it died overnight. and the lesson is about authentic faith vs performative religion. i have follow up questions but they can wait because that was genuinely profound.", time: "8:26 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "thomas's follow up questions \"can wait\" is the highest praise thomas has ever given anything 😂", time: "8:27 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "also he was still hungry btw. nobody has addressed this. did he ever eat breakfast.", time: "8:28 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i have figs in the supply bag. i've had them the whole time. but it felt weird to bring it up after the tree incident.", time: "8:29 AM" },
  { sender: "James", color: "#2DD4BF", msg: "JUDAS. YOU HAD FIGS. THIS ENTIRE TIME. AND SAID NOTHING.", time: "8:29 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "THE MAN WAS CURSING TREES JAMES. I WAS NOT ABOUT TO PULL OUT A FIG IN THAT MOMENT.", time: "8:30 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "\"i was not about to pull out a fig in that moment\" is the funniest sentence in the history of this group chat 💀💀💀", time: "8:30 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "so he cursed a tree for not having figs, it died overnight, it was actually a metaphor for the pharisees, and judas had figs in the bag THE ENTIRE TIME but was too scared to say anything?? this is the greatest story ever told and i am not being dramatic. 💅", time: "8:35 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i'd like to see ANY of you offer snacks to a man who's actively executing a plant", time: "8:35 AM" },
  { type: "system", text: "Read by everyone" },
],
});
