// Episode: That Time Jesus Chose Violence
// Scripture: Mark 11:15-19 · Matt 21:12-17 · John 2:13-22
window.EPISODES.push({
  id: "temple",
  title: "That Time Jesus Chose Violence",
  subtitle: "First degree furniture assault",
  emoji: "🪑💥🕊️",
  location: "The Temple, Jerusalem",
  scripture: "Mark 11:15-19 · Matt 21:12-17 · John 2:13-22",
  time: "9:05 AM",
  battery: 80,
  messages: [
  { type: "system", text: "Today, 9:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "heading into the temple. Jesus is up front. normal day. good vibes.", time: "9:05 AM" },
  { sender: "John", color: "#34D399", msg: "beautiful morning for it honestly. Passover week. love this time of year.", time: "9:06 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "the courts are PACKED with merchants. money changers everywhere. livestock section is wild. smells insane.", time: "9:08 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the exchange rates these guys are charging are criminal btw. 15% markup on temple currency?? i used to work in finance and even I wouldn't do that.", time: "9:09 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "you literally would have done that matthew", time: "9:09 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "ok i WOULD have but i would have felt bad about it", time: "9:10 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "what's today's itinerary btw. teaching? prayer? is there a schedule.", time: "9:11 AM" },
  { sender: "Philip", color: "#C084FC", msg: "thomas there has never once been a schedule", time: "9:11 AM" },
  { sender: "James", color: "#2DD4BF", msg: "uh. guys. is Jesus ok? he's stopped walking and he's just... staring at the merchant section.", time: "9:14 AM" },
  { sender: "John", color: "#34D399", msg: "he looks different. like his whole face just changed.", time: "9:14 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "i've been with him for two years and i've never seen him look like that", time: "9:15 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "like mad? or", time: "9:15 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "like FURIOUS andrew. like righteous fury. his jaw is clenched.", time: "9:16 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "should... should someone talk to him or", time: "9:16 AM" },
  { sender: "James", color: "#2DD4BF", msg: "YOU go talk to him. i'm not going near that energy.", time: "9:17 AM" },
  { sender: "Philip", color: "#C084FC", msg: "wait what is he picking up", time: "9:18 AM" },
  { sender: "John", color: "#34D399", msg: "are those cords?", time: "9:18 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "he's. he's braiding them together.", time: "9:18 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "is he making what i think he's making", time: "9:19 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "that's a whip. he is making a whip. in the temple. with his hands. right now.", time: "9:19 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "THIS WAS NOT ON THE ITINERARY", time: "9:19 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "THERE WAS NO ITINERARY THADDAEUS I'VE BEEN SAYING THIS", time: "9:20 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "the handmade whip is giving very intentional energy. this is not a snap decision. he came here with a PLAN.", time: "9:20 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he's walking toward the money changers' tables", time: "9:22 AM" },
  { sender: "James", color: "#2DD4BF", msg: "oh no", time: "9:22 AM" },
  { sender: "James", color: "#2DD4BF", msg: "oh NO", time: "9:22 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "HE FLIPPED THE TABLE", time: "9:23 AM" },
  { sender: "John", color: "#34D399", msg: "COINS EVERYWHERE 😭😭😭", time: "9:23 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "HE FLIPPED ANOTHER ONE", time: "9:23 AM" },
  { sender: "Philip", color: "#C084FC", msg: "THAT'S THREE TABLES", time: "9:23 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "FOUR. FOUR TABLES. HE IS SPEEDRUNNING THROUGH THE MONEY CHANGERS.", time: "9:24 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "this is the greatest day of my LIFE", time: "9:24 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "THERE ARE COINS ROLLING EVERYWHERE. people are on their hands and knees trying to grab them. it's CHAOS.", time: "9:24 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "the money 😰", time: "9:25 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "all that money on the ground 😰😰", time: "9:25 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "judas this is not the time to be thinking about the money", time: "9:25 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "he's yelling \"MY HOUSE SHALL BE CALLED A HOUSE OF PRAYER BUT YOU HAVE MADE IT A DEN OF ROBBERS\" and his voice is echoing off every wall in this place", time: "9:26 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "HE'S IN THE LIVESTOCK SECTION NOW", time: "9:27 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "HE OPENED THE DOVE CAGES", time: "9:27 AM" },
  { sender: "John", color: "#34D399", msg: "DOVES. EVERYWHERE. THERE ARE DOVES FLYING ALL OVER THE TEMPLE. 🕊️🕊️🕊️🕊️🕊️🕊️", time: "9:27 AM" },
  { sender: "James", color: "#2DD4BF", msg: "one just landed on a pharisee's head i am going to LOSE IT 😂", time: "9:28 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "the cattle are LOOSE. someone's ox just ran through the court of the gentiles at full speed.", time: "9:28 AM" },
  { sender: "Philip", color: "#C084FC", msg: "a sheep just knocked over a scribe 💀💀💀", time: "9:28 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "i need everyone to know that i am standing completely still against a pillar trying to be invisible", time: "9:29 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "same. i'm behind a column. i can see the whole thing from here and it is CINEMATIC.", time: "9:29 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "i've been anti-establishment my whole life and i have NEVER seen anyone go this hard. he's flipping tables like they're PANCAKES.", time: "9:30 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "one of the money changers just tried to grab his coins off the ground and Jesus kicked the pile 😭", time: "9:30 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "KICKED THE PILE 💀💀💀 THAT IS SAVAGE", time: "9:31 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "ok i'm watching a dove merchant try to catch his doves with a basket and i genuinely can't tell if i should help him or if that makes me a traitor to the cause", time: "9:31 AM" },
  { sender: "James", color: "#2DD4BF", msg: "do NOT help the dove man matthew", time: "9:32 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the pharisees are FUMING. they're huddled in the corner whispering and pointing at him.", time: "9:33 AM" },
  { sender: "John", color: "#34D399", msg: "one of them just said \"by what authority do you do these things\" and Jesus gave them THE look", time: "9:34 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "to be fair \"by what authority\" is a reasonable question when someone is flipping furniture in a house of worship", time: "9:34 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "thomas whose side are you on", time: "9:35 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "HIS SIDE. i'm just saying from a legal standpoint there are questions.", time: "9:35 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "legal standpoint 😂 thomas there are doves in the rafters and cattle in the courtyard. we're past legal standpoints.", time: "9:36 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i'm still looking at all this money on the ground. just so everyone knows. it's a LOT of money.", time: "9:37 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "JUDAS STOP LOOKING AT THE MONEY", time: "9:37 AM" },
  { sender: "James", color: "#2DD4BF", msg: "how many tables is that now. has anyone been counting.", time: "9:38 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "i lost count after seven but the dove situation alone is at least twelve cages", time: "9:38 AM" },
  { sender: "Philip", color: "#C084FC", msg: "a money changer just slipped on his own coins trying to run away. i'm crying. actual tears.", time: "9:39 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "the lamb merchants are trying to herd their sheep back and the sheep are NOT cooperating. one just went up the steps toward the holy place 😭", time: "9:40 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "i am having very complicated feelings. as a former finance guy watching a financial district get dismantled in real time. part of me is horrified. the rest of me is cheering.", time: "9:41 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok he's stopped flipping tables. he's just standing in the middle of the court breathing hard. whip still in hand. tables everywhere. coins everywhere. doves everywhere. livestock loose. it looks like a TORNADO went through.", time: "9:43 AM" },
  { sender: "John", color: "#34D399", msg: "the silence right now is DEAFENING. nobody is moving. even the pharisees shut up.", time: "9:44 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "he looks like a painting rn. just standing there in the wreckage. this is the hardest anyone has ever gone in the history of going hard.", time: "9:44 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "ok now blind and lame people are coming up to him and HE'S HEALING THEM. in the middle of the flipped tables. like he just redecorated and now he's back to business.", time: "9:47 AM" },
  { sender: "James", color: "#2DD4BF", msg: "table flip → dove liberation → cattle stampede → heal the sick. what a MORNING.", time: "9:48 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "so to be clear the sequence of events was: entered temple, assessed situation, handcrafted a weapon, destroyed the marketplace, freed the animals, terrified the religious establishment, and is now calmly healing people. and it's not even 10 AM.", time: "9:49 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "when you put it like that it's honestly unhinged 😂", time: "9:49 AM" },
  { sender: "Philip", color: "#C084FC", msg: "children in the temple are literally chanting \"Hosanna to the Son of David\" and the pharisees look like they're going to have a stroke", time: "9:50 AM" },
  { sender: "Thaddaeus", color: "#4ADE80", msg: "the kids are CHANTING while the pharisees are SEETHING while doves are flying overhead while a sheep wanders by. this is a renaissance painting.", time: "9:51 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "the pharisees just asked him \"do you hear what these children are saying?\" and he said \"have you never read, 'from the lips of children and infants you, Lord, have called forth your praise'?\" and WALKED OUT.", time: "9:52 AM" },
  { sender: "Andrew", color: "#FBBF24", msg: "THE MIC DROP EXIT 😭😭😭", time: "9:52 AM" },
  { sender: "John", color: "#34D399", msg: "he quoted scripture AT them and then just LEFT. with the whip. he took the whip home.", time: "9:53 AM" },
  { sender: "James", color: "#2DD4BF", msg: "he KEPT the whip?? 💀", time: "9:53 AM" },
  { sender: "Simon the Zealot", color: "#F87171", msg: "king behavior. you keep the whip. that's a souvenir.", time: "9:54 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "so are we just... following him out? do we help clean up? what's the etiquette when your rabbi destroys a marketplace.", time: "9:55 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "we follow him thomas. we always follow him. ESPECIALLY after that.", time: "9:55 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "i just want to note that i did not pick up any of the money on the ground. it was very hard but i didn't.", time: "9:56 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "do you want a medal judas", time: "9:56 AM" },
  { sender: "Judas", color: "#94A3B8", msg: "a little acknowledgment would be nice yes", time: "9:57 AM" },
  { sender: "Nathanael", color: "#FB923C", msg: "there's still a dove on the pharisee's head btw. nobody has told him. i'm choosing not to.", time: "9:58 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "i was buying spices in the market and missed the ENTIRE thing. came back to flipped tables, loose sheep, doves in the rafters, coins on the floor, and twelve men standing around looking shook. can someone explain why there's a goat in the court of women.", time: "10:05 AM" },
  { sender: "Peter", color: "#60A5FA", msg: "jesus flipped every table in the temple, freed the animals, made a whip from scratch, called out the entire religious establishment, healed people in the rubble, and left", time: "10:06 AM" },
  { sender: "Mary Magdalene", color: "#FF6B6B", msg: "and i MISSED it?? this is the worst day of my life. 💅", time: "10:06 AM" },
  { sender: "Thomas", color: "#A78BFA", msg: "can we talk about the fact that he SAT DOWN and BRAIDED a whip before any of this. that's premeditated table flipping. that's first degree furniture assault.", time: "10:08 AM" },
  { sender: "James", color: "#2DD4BF", msg: "\"first degree furniture assault\" is going on your tombstone thomas", time: "10:08 AM" },
  { sender: "Matthew", color: "#818CF8", msg: "writing it all down. this chapter is going to be called \"that time Jesus chose violence\" in my first draft", time: "10:10 AM" },
  { type: "system", text: "Read by everyone" },
],
});
